"""Chapter 1: mechanical foundations; source and review owned by this worker."""
from coursekit import P, H, E, T, cite, defense, note


def eq(identifier, tex, en, zh, kind, typ, labels, notes, cap_en, cap_zh):
    return E(identifier, tex, en, zh, kind,
             {"type": typ, "labels": labels, "notes": notes}, cap_en, cap_zh)


body = H("1.1 Identify the actuator before choosing an equation", "1.1 先辨认执行机制，再选择方程", "mechanisms")
body += P(
    "Our objective is to establish the mechanical part of the transfer chain: how a cavity accelerates its surrounding liquid, how boundaries select a direction, and what extra information is needed to predict a usable jet. A PFC droplet begins as a liquid inclusion with a finite inventory. A bubble is a cavity containing vapor, permanent gas, or both. Their radii describe different physical objects; a bubble radius is not a measure of the remaining PFC mass.",
    "本章建立转印链中的力学部分：空腔如何加速周围液体，边界如何选定方向，以及预测可用射流还需要哪些信息。PFC 液滴最初是具有有限物质库存的液态夹杂物。气泡是含蒸气、非凝结气体或两者的空腔。两者半径描述不同物理对象；气泡半径不能代表剩余 PFC 质量。")
body += P(
    "Pressure-driven cavitation and thermally initiated vaporization can both produce an inertially moving cavity. Here the phrase laser-induced cavitation includes heating, activation, growth, collapse and possible jetting, while the activation mechanism must be identified separately. Chapter 2 supplies absorption, heat transfer, nucleation and finite phase inventory. This chapter first treats internal pressure as a supplied input, so the mechanical derivation can be reconstructed without inventing an optical efficiency.",
    "压力驱动空化与热诱导汽化均可形成具有惯性运动的空腔。本课程的“激光诱导空化”包括加热、激活、增长、塌缩以及可能的射流，但激活机制必须单独辨认。第二章补充吸收、传热、成核和有限相变库存。本章先把内部压力视为给定输入，从而在不虚构光能转换效率的条件下完整重建力学推导。")
body += T(
    [("Mechanism", "机制"), ("Moving liquid and boundary", "运动液体与边界"), ("What establishes the classification", "判定依据")],
    [
        [("Expansion-driven ejection", "膨胀驱动喷射"), ("The growing cavity displaces carrier toward an outlet or meniscus; the emitted jet is outside the cavity.", "增长空腔将载液推向出口或弯月面；喷出射流位于空腔之外。"), ("Track cavity growth and the outgoing liquid together.", "同时追踪空腔增长与向外喷出的液体。")],
        [("Collapse-driven re-entrant jet", "塌缩驱动的再入射流"), ("An asymmetric liquid interface penetrates the collapsing cavity and can strike its opposite side or a wall.", "非对称液体界面穿入塌缩空腔，可撞击另一侧界面或壁面。"), ("Show penetration into the cavity; do not rename it an external transfer jet.", "观测射流穿入空腔；不能直接把它称为外部转印射流。")],
        [("Sealed-cavity inflation", "密闭空腔膨胀"), ("Pressure deforms an intact membrane or stamp; liquid need not cross a gap.", "压力使完整膜或印章变形；液体不必跨越间隙。"), ("Locate the closed boundary and the transmitted deformation.", "确定封闭边界及其传递的变形。")],
        [("Liquid-bridge stretching", "液桥拉伸"), ("A moving solid pulls a filament; the filament need not originate as a cavitation jet.", "运动固体拉出液丝；液丝不一定起源于空化射流。"), ("Establish which moved first: the liquid tip or the solid.", "辨明最先运动的是液体前端还是固体。")],
    ])
body += P(
    "A bright cavity and a detached payload alone cannot distinguish these mechanisms. The required observations are the cavity boundary, liquid trajectories, outlet, receiving surface and event sequence. The capillary-meniscus study and asymmetric-collapse study cited here address different geometries; their findings are useful only after the boundary conditions are matched. "+cite("r3")+" "+cite("r4"),
    "仅有明亮空腔与已脱离载荷，无法区分这些机制。需要观测空腔边界、液体轨迹、出口、受载表面及事件顺序。这里引用的毛细管弯月面研究与非对称塌缩研究对应不同几何结构；匹配边界条件之后，其结论才适用。 "+cite("r3")+" "+cite("r4"))

body += H("1.2 Define the spherical control and its symbols", "1.2 定义球形对照体系与符号", "spherical-control")
body += P(
    "The first model is one spherical cavity in an infinite, incompressible Newtonian carrier. The center is fixed; the radial coordinate increases from the center into the liquid. Positive wall velocity means expansion. Density, viscosity and effective surface tension are constant. Gravity, bulk liquid vorticity, phase-transfer velocity slip and gas-side viscous stress are omitted. The bubble pressure is uniform in space but may depend on time. This is a single transient model; no periodic acoustic forcing is assumed.",
    "第一个模型为无限、不可压缩牛顿载液中的单个球形空腔。中心固定；径向坐标从中心向液体外侧增加。壁面速度为正表示膨胀。密度、黏度和有效表面张力为常数。忽略重力、液体体内涡量、相变造成的速度滑移及气相黏性应力。气泡压力空间均匀，但可随时间变化。本模型描述单次瞬态，不假设周期声驱动。")
body += T(
    [("Symbols and roles", "符号及作用"), ("Definition and units", "定义与单位")],
    [
        [(r"$t,r,R,\dot R,\ddot R$", r"$t,r,R,\dot R,\ddot R$"), ("Time (s), liquid radial coordinate (m), cavity radius (m), wall speed (m s⁻¹), wall acceleration (m s⁻²). Dots denote time derivatives.", "时间（s）、液体径向坐标（m）、空腔半径（m）、壁面速度（m s⁻¹）与壁面加速度（m s⁻²）。上方圆点表示时间导数。")],
        [(r"$\rho,\mu,\sigma$", r"$\rho,\mu,\sigma$"), ("Carrier density (kg m⁻³), carrier dynamic viscosity (Pa s), effective bubble–carrier surface tension (N m⁻¹).", "载液密度（kg m⁻³）、载液动力黏度（Pa s）与有效气泡—载液表面张力（N m⁻¹）。")],
        [(r"$p_b,p_l,p_\infty$", r"$p_b,p_l,p_\infty$"), ("Bubble, adjacent liquid and far-field absolute pressures (Pa). Only explicitly subtracted differences drive mechanics.", "气泡、邻近液体与远场的绝对压力（Pa）。力学驱动力来自明确写出的压力差。")],
        [(r"$u,\phi,V_b,K_l,E_\sigma$", r"$u,\phi,V_b,K_l,E_\sigma$"), ("Radial velocity (m s⁻¹), velocity potential (m² s⁻¹), cavity volume (m³), carrier kinetic energy (J), interface energy (J).", "径向速度（m s⁻¹）、速度势（m² s⁻¹）、空腔体积（m³）、载液动能（J）与界面能（J）。")],
        [(r"$R_{\max},p_v,\Delta p_c,t_c,E_B$", r"$R_{\max},p_v,\Delta p_c,t_c,E_B$"), ("Maximum radius (m), stipulated constant vapor pressure (Pa), positive collapse pressure difference (Pa), collapse time (s), pressure-work scale (J). Subscripts identify physical roles.", "最大半径（m）、假设为常数的蒸气压（Pa）、正的塌缩压差（Pa）、塌缩时间（s）与压力功尺度（J）。下标表示物理作用。")],
        [(r"$\boldsymbol x,\boldsymbol u,\Pi,\Gamma,\boldsymbol n,\kappa$", r"$\boldsymbol x,\boldsymbol u,\Pi,\Gamma,\boldsymbol n,\kappa$"), ("Spatial position (m), velocity vector (m s⁻¹), pressure impulse (Pa s), liquid–gas interface, unit normal from liquid into gas, signed sum of principal curvatures (m⁻¹).", "空间位置（m）、速度矢量（m s⁻¹）、压力冲量（Pa s）、液—气界面、由液体指向气体的单位法向，以及带符号的两主曲率之和（m⁻¹）。")],
    ])
body += P(
    "Ordinary superscripts are powers, bold symbols are vectors or tensors, and π is the dimensionless circle constant. Spatial gradient, divergence and Laplacian have their usual Cartesian meanings; partial time derivatives hold position fixed. Every display repeats its local definitions, including any new integration variables. The supplied initial radius is positive, which permits division by radius until the model reaches its excluded zero-radius limit.",
    "通常的上标表示幂；粗体符号表示矢量或张量；π 是无量纲圆周率。空间梯度、散度与拉普拉斯算子采用通常的笛卡尔定义；时间偏导保持空间位置固定。每个公式前重复其局部符号定义，包括新引入的积分变量。给定初始半径为正，因此在到达模型所排除的零半径极限之前，可以除以半径。")
body += eq("C1-E01", r"R(0)=R_0>0,\qquad \dot R(0)=U_0,\qquad u(r,t)\to0,\quad p(r,t)\to p_\infty(t)\quad(r\to\infty)",
    r"$R$ is the cavity radius (m); $t$ is time (s), with 0 the chosen initial instant; $R_0$ is its prescribed positive initial value (m); $\dot R$ is wall speed and $U_0$ its initial value (m s⁻¹); $r$ is radial position (m); $u$ is radial liquid speed (m s⁻¹); $p$ is liquid pressure (Pa); $p_\infty$ is prescribed far-field pressure (Pa). The arrow denotes the far-field limit.",
    r"$R$ 为空腔半径（m）；$t$ 为时间（s），0 为选定的初始时刻；$R_0$ 为给定的正初始半径（m）；$\dot R$ 为壁面速度，$U_0$ 为其初值（m s⁻¹）；$r$ 为径向位置（m）；$u$ 为液体径向速度（m s⁻¹）；$p$ 为液体压力（Pa）；$p_\infty$ 为给定远场压力（Pa）。箭头表示远场极限。",
    "Prescribed initial and boundary conditions", "sphere", ["R(t)", "R₀ > 0", "Ṙ(0) = U₀", "r → ∞", "u → 0", "p → p∞", "t = 0"],
    ["Radial direction points from bubble center into carrier", "Far-field pressure is an input, not a laser calculation"],
    "The evolving spherical boundary and the prescribed far-field state.", "运动球形边界与给定的远场状态。")

body += H("1.3 Derive Rayleigh–Plesset without hiding the derivative", "1.3 不省略关键导数，推导 Rayleigh–Plesset 方程", "rayleigh-plesset")
body += P("<strong>Step 1 — Conservation of carrier volume.</strong> With radial symmetry, incompressibility makes the radial volume flux independent of radius. Integrate its radial derivative, and use the no-slip-in-the-normal-direction condition at the interface. No vapor density is required for this carrier-flow calculation.",
    "<strong>步骤 1——载液体积守恒。</strong> 在径向对称条件下，不可压缩性使径向体积流量与半径无关。积分其径向导数，再应用界面法向无速度滑移条件。这一载液流动计算不需要蒸气密度。")
body += eq("C1-E02", r"\frac{1}{r^2}\frac{\partial(r^2u)}{\partial r}=0\ \Longrightarrow\ r^2u=C(t),\qquad u(R,t)=\dot R\ \Longrightarrow\ C(t)=R^2\dot R,\qquad u(r,t)=\frac{R^2\dot R}{r^2}",
    r"$r\ge R(t)>0$ is radial position (m); $R$ is cavity radius (m); $t$ is time (s); $u$ is radial carrier velocity (m s⁻¹); $\dot R$ is wall speed (m s⁻¹); $C(t)$ is the radius-independent flux factor (m³ s⁻¹), not a material constant; $\partial/\partial r$ differentiates at fixed time. The implication arrows indicate integration and use of the interface condition.",
    r"$r\ge R(t)>0$ 为径向位置（m）；$R$ 为空腔半径（m）；$t$ 为时间（s）；$u$ 为载液径向速度（m s⁻¹）；$\dot R$ 为壁面速度（m s⁻¹）；$C(t)$ 为与径向位置无关的流量因子（m³ s⁻¹），并非材料常数；$\partial/\partial r$ 表示固定时间下的径向求导。箭头表示积分及应用界面条件。",
    "Exact continuity within the spherical model", "sphere", ["r ≥ R", "u(r,t)", "Ṙ", "C(t) = R²Ṙ", "t", "r²u = constant"], ["Concentric surfaces carry the same volume flux", "At r = 2R the speed is Ṙ/4"], "Inverse-square velocity decay places the inertia in the surrounding carrier.", "速度按距离平方反比衰减，惯性来自周围载液。")
body += P("<strong>Step 2 — Fix the potential's reference.</strong> Integrate the velocity from infinity to the chosen position. The resulting potential is valid in the liquid exterior. A constant added only in time is fixed by choosing zero potential at infinity.",
    "<strong>步骤 2——固定速度势的参考值。</strong> 从无穷远积分速度至选定位置。所得速度势适用于液体外域。通过选取无穷远处速度势为零，固定仅随时间变化的附加常数。")
body += eq("C1-E03", r"\phi(r,t)=\int_\infty^r u(s,t)\,ds=R^2\dot R\int_\infty^r s^{-2}\,ds=-\frac{R^2\dot R}{r},\qquad \frac{\partial\phi}{\partial r}=u",
    r"$\phi$ is velocity potential (m² s⁻¹); $r$ is liquid radial position and $R$ cavity radius (m); $t$ is time (s); $s$ is a dummy radial integration coordinate (m); $u$ is radial velocity (m s⁻¹); $\dot R$ is wall speed (m s⁻¹); the integral is an improper integral convergent for $r\ge R>0$; $\partial/\partial r$ is the fixed-time spatial derivative.",
    r"$\phi$ 为速度势（m² s⁻¹）；$r$ 为液体径向位置，$R$ 为空腔半径（m）；$t$ 为时间（s）；$s$ 为径向积分哑变量（m）；$u$ 为径向速度（m s⁻¹）；$\dot R$ 为壁面速度（m s⁻¹）；该广义积分在 $r\ge R>0$ 时收敛；$\partial/\partial r$ 为固定时间的空间导数。",
    "Derived velocity potential", "sphere", ["φ(r,t)", "r", "R", "Ṙ", "s: integration radius", "u = ∂rφ", "φ∞ = 0", "t"], ["Differentiate spatially to recover the radial flow"], "The potential reference is fixed at infinity before differentiation.", "在求导之前，先固定无穷远处的速度势参考值。")
body += P("<strong>Step 3 — Differentiate at a fixed observation point.</strong> The Eulerian derivative differentiates the numerator while holding the denominator fixed; only then is the observation point set equal to the instantaneous wall radius. Differentiating the wall value instead follows a moving point and includes an extra convective contribution.",
    "<strong>步骤 3——在固定观察点求导。</strong> 欧拉时间导数只对分子求导，同时保持分母固定；之后才将观察点设为当前壁面半径。直接对壁面取值求导，相当于跟随运动点，会多出一个对流贡献。")
body += eq("C1-E04", r"\left.\frac{\partial\phi}{\partial t}\right|_r=-\frac{2R\dot R^2+R^2\ddot R}{r},\qquad \left.\frac{\partial\phi}{\partial t}\right|_{r=R}=-(2\dot R^2+R\ddot R),\qquad \frac{d\phi(R(t),t)}{dt}=-\dot R^2-R\ddot R",
    r"$\phi$ is velocity potential (m² s⁻¹); $t$ is time (s); $r$ is fixed radial position, $R(t)>0$ is moving cavity radius (m); $\dot R$ and $\ddot R$ are wall speed (m s⁻¹) and acceleration (m s⁻²); vertical bars specify where the derivative is taken or evaluated; $d/dt$ follows the moving wall value. Each derivative has units m² s⁻².",
    r"$\phi$ 为速度势（m² s⁻¹）；$t$ 为时间（s）；$r$ 为固定径向位置，$R(t)>0$ 为运动空腔半径（m）；$\dot R$ 与 $\ddot R$ 分别为壁面速度（m s⁻¹）和加速度（m s⁻²）；竖线表示求导或取值条件；$d/dt$ 跟随运动壁面的取值。各导数的单位均为 m² s⁻²。",
    "Exact Eulerian and moving-point derivatives", "sphere", ["Fixed r", "Moving R(t)", "φ", "Ṙ", "R̈", "∂tφ at fixed r", "dφ(R,t)/dt", "t"], ["Take the partial derivative before setting r = R", "The moving-point derivative differs by Ṙ²"], "A fixed liquid observation point and a moving interface point have different time derivatives.", "固定液体观察点与运动界面点对应不同的时间导数。")
body += P("<strong>Step 4 — Integrate the radial momentum equation.</strong> This radial field is irrotational and its vector Laplacian vanishes in the exterior, so the bulk viscous force vanishes even though viscous normal stress and dissipation remain. Unsteady Bernoulli, referenced to infinity, then supplies the liquid-side pressure. Substitute the fixed-position derivative and the wall velocity; the coefficient is two minus one half.",
    "<strong>步骤 4——积分径向动量方程。</strong> 此径向场无旋，且其矢量拉普拉斯在外域为零，因此体内黏性力为零，但黏性法向应力和耗散依然存在。以无穷远为参考的非定常伯努利方程给出液体侧压力。代入固定位置时间导数与壁面速度后，系数由二减去二分之一得到。")
body += eq("C1-E05", r"\frac{p_l-p_\infty}{\rho}=-\left.\frac{\partial\phi}{\partial t}\right|_{r=R}-\frac{u(R,t)^2}{2}=2\dot R^2+R\ddot R-\frac{\dot R^2}{2}=R\ddot R+\frac32\dot R^2",
    r"$p_l$ is liquid pressure at the wall and $p_\infty$ far-field pressure (Pa); $\rho>0$ is carrier density (kg m⁻³); $\phi$ is velocity potential (m² s⁻¹); $t$ is time (s); $r$ is radial position and $R>0$ cavity radius (m); $u$ is radial velocity and $\dot R$ wall speed (m s⁻¹); $\ddot R$ is wall acceleration (m s⁻²); $\partial_t$ is taken at fixed position before wall evaluation.",
    r"$p_l$ 为壁面液体压力，$p_\infty$ 为远场压力（Pa）；$\rho>0$ 为载液密度（kg m⁻³）；$\phi$ 为速度势（m² s⁻¹）；$t$ 为时间（s）；$r$ 为径向位置，$R>0$ 为空腔半径（m）；$u$ 为径向速度，$\dot R$ 为壁面速度（m s⁻¹）；$\ddot R$ 为壁面加速度（m s⁻²）；$\partial_t$ 必须先在固定位置求导，再于壁面取值。",
    "Derived inertial pressure", "sphere", ["pl at r = R", "p∞", "ρ", "φ", "u(R,t) = Ṙ", "R̈", "r", "t"], ["R R̈ and 3Ṙ²/2 each have units m²/s²"], "Liquid inertia relates the interface pressure to wall acceleration and squared speed.", "液体惯性把界面压力与壁面加速度及速度平方联系起来。")
body += P("<strong>Step 5 — Apply the clean-interface normal stress.</strong> The radial rate of strain at the wall is negative during expansion. The capillary jump lowers liquid-side pressure relative to bubble pressure. Equal normal traction, including Newtonian viscous stress, gives the following pair of relations.",
    "<strong>步骤 5——应用洁净界面的法向应力。</strong> 膨胀时壁面径向应变率为负。毛细压力跃变使液体侧压力低于气泡压力。包含牛顿黏性应力的法向牵引力平衡给出以下关系。")
body += eq("C1-E06", r"\left.\frac{\partial u}{\partial r}\right|_{r=R}=\left.-\frac{2R^2\dot R}{r^3}\right|_{r=R}=-\frac{2\dot R}{R},\qquad p_l=p_b-\frac{2\sigma}{R}+2\mu\left.\frac{\partial u}{\partial r}\right|_{r=R}=p_b-\frac{2\sigma}{R}-\frac{4\mu\dot R}{R}",
    r"$u$ is radial velocity and $\dot R$ wall speed (m s⁻¹); $r$ is radial position and $R>0$ cavity radius (m); $p_l,p_b$ are liquid-side and uniform bubble pressures (Pa); $\sigma\ge0$ is surface tension (N m⁻¹); $\mu\ge0$ is carrier viscosity (Pa s); $\partial_r u$ is radial strain rate (s⁻¹); wall evaluation is performed at $r=R$.",
    r"$u$ 为径向速度，$\dot R$ 为壁面速度（m s⁻¹）；$r$ 为径向位置，$R>0$ 为空腔半径（m）；$p_l,p_b$ 分别为液体侧与空间均匀的气泡压力（Pa）；$\sigma\ge0$ 为表面张力（N m⁻¹）；$\mu\ge0$ 为载液黏度（Pa s）；$\partial_r u$ 为径向应变率（s⁻¹）；壁面取值在 $r=R$ 处进行。",
    "Newtonian stress and capillary boundary condition", "sphere", ["pb inside", "pl outside", "R", "r", "u", "Ṙ", "2σ/R", "4μṘ/R", "∂ru = −2Ṙ/R"], ["Viscous stress changes sign when the wall reverses"], "Capillary and viscous stresses act at the interface even when the radial bulk viscous force is zero.", "即使径向体内黏性力为零，毛细与黏性应力仍作用于界面。")
body += P("<strong>Step 6 — Combine inertia and traction.</strong> Substitute Eq. (C1-E06) into Eq. (C1-E05) and multiply by carrier density. This closes the radial momentum balance, but not the internal pressure. The surrounding aqueous carrier sets the inertia; replacing its density with liquid PFC density would describe a different exterior domain.",
    "<strong>步骤 6——联立惯性与牵引力。</strong> 将式（C1-E06）代入式（C1-E05），再乘以载液密度。这闭合了径向动量平衡，却没有闭合内部压力。惯性由周围水性载液决定；若换成液态 PFC 密度，就相当于改换了外部流动区域。")
body += eq("C1-E07", r"\rho\left(R\ddot R+\frac32\dot R^2\right)=p_b-p_\infty-\frac{2\sigma}{R}-\frac{4\mu\dot R}{R}",
    r"$\rho>0$ is carrier density (kg m⁻³); $R>0$ is cavity radius (m); $\dot R,\ddot R$ are wall speed (m s⁻¹) and acceleration (m s⁻²); $p_b,p_\infty$ are bubble and far-field pressures (Pa); $\sigma$ is constant surface tension (N m⁻¹); $\mu$ is constant carrier viscosity (Pa s). Every term is a pressure.",
    r"$\rho>0$ 为载液密度（kg m⁻³）；$R>0$ 为空腔半径（m）；$\dot R,\ddot R$ 分别为壁面速度（m s⁻¹）和加速度（m s⁻²）；$p_b,p_\infty$ 为气泡与远场压力（Pa）；$\sigma$ 为常数表面张力（N m⁻¹）；$\mu$ 为常数载液黏度（Pa s）。各项均具有压力单位。",
    "Rayleigh–Plesset under the declared assumptions", "sphere", ["ρ carrier", "R", "Ṙ", "R̈", "pb", "p∞", "2σ/R", "4μṘ/R"], ["Outward is positive", "The equation predicts radius, not jet shape"], "The spherical pressure–inertia balance has a scalar radial state.", "球形压力—惯性平衡只具有标量径向状态。")
body += P(
    "Dimensions give density times length times acceleration = Pa; surface tension divided by radius and viscosity times speed divided by radius are also Pa. At rest, balance requires bubble pressure to exceed far-field pressure by the capillary jump. During inward motion, the viscous pressure term is positive and resists collapse. A negative right side is not alone the acceleration: the squared-speed term must also be subtracted when solving for acceleration. These results agree with the classical spherical treatment. "+cite("r1")+' <a class="citation" href="https://media.library.caltech.edu/CaltechBOOK%3A1995.001/chap2.htm">[Brennen, Ch. 2]</a>',
    "量纲检查表明，密度乘长度乘加速度的单位为 Pa；表面张力除以半径、以及黏度乘速度除以半径也均为 Pa。静止时，气泡压力必须比远场压力高出毛细压力跃变。向内运动时，黏性压力项为正，阻碍塌缩。右端为负并不能单独给出加速度；求解加速度时还必须减去速度平方项。这些结果与经典球形理论一致。 "+cite("r1")+' <a class="citation" href="https://media.library.caltech.edu/CaltechBOOK%3A1995.001/chap2.htm">[Brennen，第 2 章]</a>')
body += eq("C1-E08", r"p_b=p_{v,\mathrm{PFC}}+p_{v,w}+p_g",
    r"$p_b$ is uniform total bubble pressure (Pa); $p_{v,\mathrm{PFC}}$ is the PFC-vapor partial pressure, $p_{v,w}$ water-vapor partial pressure, and $p_g$ permanent-gas partial pressure (all Pa). Subscript $v$ labels vapor, PFC its chemical family, $w$ water, and $g$ noncondensable gas. Additivity assumes a gas-mixture pressure description with the stated partial pressures.",
    r"$p_b$ 为空间均匀的气泡总压力（Pa）；$p_{v,\mathrm{PFC}}$ 为 PFC 蒸气分压，$p_{v,w}$ 为水蒸气分压，$p_g$ 为非凝结气体分压（均为 Pa）。下标 $v$ 表示蒸气，PFC 表示该化学物质族，$w$ 表示水，$g$ 表示非凝结气体。相加关系采用具有上述分压定义的气体混合物压力描述。",
    "Pressure composition requiring thermodynamic closure", "phase", ["pb", "pv,PFC", "pv,w", "pg", "Finite PFC liquid inventory"], ["Partial pressures need mass and energy histories", "No fixed-mass gas law is automatically a vaporization law"], "The mechanical input comes from the evolving contents, not from radius alone.", "力学输入来自不断变化的气泡内容物，不能仅由半径决定。")
body += P("A polytropic fixed-mass gas law is a useful gas-bubble control only when its mass and heat-transfer assumptions apply. Evaporation and condensation exchange mass and latent heat; they cannot be silently replaced by a permanent-gas law. The uniform-pressure approximation itself requires internal communication fast enough compared with state evolution. Chapter 2 will state the finite-inventory closure explicitly. "+cite("r5"),
    "定质量多方气体定律只有在其质量与传热假设适用时，才能作为有用的气泡对照模型。蒸发与凝结伴随质量和潜热交换，不能悄然替换为非凝结气体定律。空间均匀压力近似本身也要求内部压力通信足够快，能够跟上状态演化。第二章将明确给出有限库存的闭合关系。 "+cite("r5"))

body += H("1.4 Derive the carrier energy balance", "1.4 推导载液能量平衡", "energy-balance")
body += P("<strong>Step 7 — Integrate kinetic energy through the whole exterior.</strong> Square the velocity from Eq. (C1-E02), multiply by the spherical volume element, and integrate. Although the domain is infinite, the remaining inverse-square integral converges. The effective moving inertia therefore belongs to carrier liquid extending beyond the cavity.",
    "<strong>步骤 7——在整个外域积分动能。</strong> 将式（C1-E02）的速度平方，乘以球形体积元，再积分。尽管区域无限，剩余的平方反比积分仍收敛。因此，有效运动惯性属于空腔之外的载液。")
body += eq("C1-E09", r"\begin{aligned}K_l&=\int_R^\infty\frac12\rho u(r,t)^2\,4\pi r^2\,dr\\&=2\pi\rho R^4\dot R^2\int_R^\infty r^{-2}\,dr\\&=2\pi\rho R^4\dot R^2\left[-\frac1r\right]_R^\infty=2\pi\rho R^3\dot R^2.\end{aligned}",
    r"$K_l$ is exterior liquid kinetic energy (J); $\rho$ is carrier density (kg m⁻³); $u$ is radial liquid speed and $\dot R$ wall speed (m s⁻¹); $t$ is time (s); $R>0$ is cavity radius, $r$ the integration radius (m); $\pi$ is the circle constant; $4\pi r^2dr$ is the spherical volume element (m³); endpoint brackets mean upper minus lower evaluation.",
    r"$K_l$ 为外部液体动能（J）；$\rho$ 为载液密度（kg m⁻³）；$u$ 为径向液体速度，$\dot R$ 为壁面速度（m s⁻¹）；$t$ 为时间（s）；$R>0$ 为空腔半径，$r$ 为积分半径（m）；$\pi$ 为圆周率；$4\pi r^2dr$ 为球形体积元（m³）；端点方括号表示上限取值减下限取值。",
    "Exact kinetic-energy integral in the spherical model", "energy", ["Kl", "ρ", "u(r,t)", "R", "Ṙ", "r: exterior shells", "4πr²dr", "t"], ["Integrate liquid shells outside the cavity", "The radial field decays enough for finite kinetic energy"], "Exterior shells contribute finite kinetic energy even in an infinite domain.", "即使外域无限，外部液壳贡献的总动能仍有限。")
body += P("<strong>Step 8 — Differentiate stored energies explicitly.</strong> Radius changes both the volume of moving liquid and its speed. Apply the product rule; separately differentiate the geometric cavity volume and interface energy. Constant surface tension is needed for the last derivative.",
    "<strong>步骤 8——明确求出储能导数。</strong> 半径变化同时改变运动液体体积和速度。应用乘积求导规则；另外分别对几何空腔体积与界面能求导。最后一项导数要求表面张力为常数。")
body += eq("C1-E10", r"\begin{aligned}\frac{dK_l}{dt}&=2\pi\rho\left(3R^2\dot R^3+2R^3\dot R\ddot R\right)=4\pi R^2\dot R\,\rho\left(R\ddot R+\frac32\dot R^2\right),\\V_b&=\frac{4\pi R^3}{3},\qquad \dot V_b=4\pi R^2\dot R,\\E_\sigma&=4\pi\sigma R^2,\qquad \frac{dE_\sigma}{dt}=8\pi\sigma R\dot R.\end{aligned}",
    r"$K_l,E_\sigma$ are liquid kinetic and interface energies (J); $t$ is time (s); $\rho$ is carrier density (kg m⁻³); $R$ is radius (m); $\dot R,\ddot R$ are speed (m s⁻¹) and acceleration (m s⁻²); $V_b$ is cavity volume (m³), $\dot V_b$ its time derivative (m³ s⁻¹); $\sigma$ is constant surface tension (N m⁻¹); $\pi$ is the circle constant. Energy derivatives are powers (W).",
    r"$K_l,E_\sigma$ 分别为液体动能与界面能（J）；$t$ 为时间（s）；$\rho$ 为载液密度（kg m⁻³）；$R$ 为半径（m）；$\dot R,\ddot R$ 分别为速度（m s⁻¹）与加速度（m s⁻²）；$V_b$ 为空腔体积（m³），$\dot V_b$ 为其时间导数（m³ s⁻¹）；$\sigma$ 为常数表面张力（N m⁻¹）；$\pi$ 为圆周率。能量的时间导数为功率（W）。",
    "Exact product-rule derivatives", "energy", ["Kl", "Eσ", "Vb", "V̇b", "R", "Ṙ", "R̈", "ρ", "σ", "t"], ["Surface energy is stored at the spherical boundary", "Volume work changes both liquid speed and effective inertia"], "Volume work couples kinetic storage, interface storage and dissipation.", "体积功耦合动能储存、界面能储存与耗散。")
body += P("<strong>Step 9 — Multiply the momentum balance by volume rate.</strong> The left side becomes the first row of Eq. (C1-E10). The capillary term becomes minus the surface-energy derivative. The viscous term is negative regardless of expansion or collapse because it contains squared speed.",
    "<strong>步骤 9——将动量平衡乘以体积变化率。</strong> 左侧成为式（C1-E10）的第一行。毛细项成为界面能导数的负值。黏性项包含速度平方，因此无论膨胀或塌缩均为负。")
body += eq("C1-E11", r"\frac{d}{dt}(K_l+E_\sigma)=(p_b-p_\infty)\dot V_b-16\pi\mu R\dot R^2,\qquad 16\pi\mu R\dot R^2\ge0",
    r"$t$ is time (s); $K_l,E_\sigma$ are kinetic and interface energies (J); $p_b,p_\infty$ are bubble and far-field pressures (Pa); $\dot V_b$ is cavity volume rate (m³ s⁻¹); $\mu\ge0$ is carrier viscosity (Pa s); $R>0$ is cavity radius (m); $\dot R$ is wall speed (m s⁻¹); $\pi$ is the circle constant. The nonnegative term is dissipated power (W).",
    r"$t$ 为时间（s）；$K_l,E_\sigma$ 为动能与界面能（J）；$p_b,p_\infty$ 为气泡与远场压力（Pa）；$\dot V_b$ 为空腔体积变化率（m³ s⁻¹）；$\mu\ge0$ 为载液黏度（Pa s）；$R>0$ 为空腔半径（m）；$\dot R$ 为壁面速度（m s⁻¹）；$\pi$ 为圆周率。非负项是耗散功率（W）。",
    "Derived mechanical-energy balance", "energy", ["Pressure work (pb − p∞)V̇b", "Kl", "Eσ", "16πμR Ṙ² ≥ 0", "pb", "p∞", "R", "Ṙ", "t"], ["Expansion or collapse may supply positive pressure work", "Viscosity always removes mechanical energy"], "The pressure source supplies mechanical work; focusing cannot create extra energy.", "压力源提供机械功；聚焦不能产生额外能量。")
body += P("The dissipation can also be checked directly. The radial strain rates are minus twice, once and once the wall-speed flux factor divided by distance cubed. Their squared sum is six times that factor squared. Integrating the Newtonian dissipation density therefore recovers exactly the loss in Eq. (C1-E11). This independent route confirms its sign and numerical coefficient.",
    "耗散还可以直接检验。三个主应变率分别为壁面速度流量因子除以距离三次方的负二倍、一倍与一倍；平方和为该因子平方的六倍。积分牛顿耗散密度，可准确恢复式（C1-E11）的损失项。这条独立推导路径检验了其符号与数值系数。")
body += eq("C1-E12", r"\begin{aligned}D_{rr}&=-\frac{2R^2\dot R}{r^3},\qquad D_{\theta\theta}=D_{\psi\psi}=\frac{R^2\dot R}{r^3},\\\mathcal D_\mu&=\int_R^\infty 2\mu\left(D_{rr}^2+D_{\theta\theta}^2+D_{\psi\psi}^2\right)4\pi r^2\,dr\\&=48\pi\mu R^4\dot R^2\int_R^\infty r^{-4}\,dr=16\pi\mu R\dot R^2.\end{aligned}",
    r"$D_{rr},D_{\theta\theta},D_{\psi\psi}$ are radial and two tangential strain-rate components (s⁻¹), with $r,\theta,\psi$ labeling spherical radial, polar and azimuthal directions; $\mathcal D_\mu$ is total viscous dissipation rate (W); $\mu$ is viscosity (Pa s); $R>0$ is radius and $r$ radial integration position (m); $\dot R$ is wall speed (m s⁻¹); $\pi$ is the circle constant. The integral is over the liquid exterior; angular labels do not reuse the potential symbol $\phi$.",
    r"$D_{rr},D_{\theta\theta},D_{\psi\psi}$ 为径向与两个切向的应变率分量（s⁻¹），其中 $r,\theta,\psi$ 分别表示球坐标径向、极角与方位角方向；$\mathcal D_\mu$ 为总黏性耗散率（W）；$\mu$ 为黏度（Pa s）；$R>0$ 为半径，$r$ 为径向积分位置（m）；$\dot R$ 为壁面速度（m s⁻¹）；$\pi$ 为圆周率。积分区域为液体外域；角向标记不复用速度势符号 $\phi$。",
    "Independent dissipation and conservation check", "energy", ["Drr", "Dθθ", "Dψψ", "Dμ", "μ", "R", "r", "Ṙ", "4πr²dr"], ["Integrate the positive dissipation density in exterior shells"], "Direct strain-rate integration verifies the mechanical-energy loss.", "直接积分应变率检验机械能损失。")
body += P("The energy balance gives a useful design warning. More confinement can redirect liquid, while also requiring more pressure work, storing elastic energy, or dissipating energy. A larger incident laser pulse does not specify how much energy reaches carrier motion. The thermodynamic source and the mechanical receiver must both be accounted for.",
    "能量平衡给出一个设计提醒：更强约束能够改变流动方向，同时也可能需要更多压力功、储存弹性能或耗散能量。入射激光脉冲增大，并不能确定有多少能量进入载液运动。必须同时核算热力学源与机械受载体系。")

body += H("1.5 Solve ideal collapse and derive the coefficient", "1.5 解出理想塌缩并推导系数", "collapse-integral")
body += P("<strong>Step 10 — Declare the reduced initial-value problem.</strong> Set time zero at maximum radius with zero wall speed. Assume constant far-field and vapor pressures with a positive difference; omit surface tension, viscosity, permanent gas and liquid compressibility. This removes thermal and phase dynamics rather than proving that they are small in PFC. A hot vapor-rich cavity may still be growing under quite different conditions.",
    "<strong>步骤 10——声明约化初值问题。</strong> 令零时刻对应最大半径，且壁面速度为零。假设远场压力与蒸气压为常数，两者差值为正；忽略表面张力、黏度、非凝结气体与液体可压缩性。这是在删除热与相变动力学，并非证明它们在 PFC 中很小。高温富蒸气空腔在完全不同的条件下仍可能增长。")
body += eq("C1-E13", r"\Delta p_c=p_\infty-p_v>0,\qquad R(0)=R_{\max},\quad \dot R(0)=0,\qquad R\ddot R+\frac32\dot R^2=-\frac{\Delta p_c}{\rho}",
    r"$\Delta p_c>0$ is constant collapse-driving pressure (Pa); $p_\infty,p_v$ are constant far-field and vapor pressures (Pa); $t=0$ is maximum-radius time (s); $R>0$ and $R_{\max}>0$ are instantaneous and maximum radii (m); $\dot R,\ddot R$ are speed (m s⁻¹) and acceleration (m s⁻²); $\rho>0$ is carrier density (kg m⁻³).",
    r"$\Delta p_c>0$ 为常数塌缩驱动压差（Pa）；$p_\infty,p_v$ 为常数远场压力与蒸气压（Pa）；$t=0$ 为最大半径时刻（s）；$R>0$ 与 $R_{\max}>0$ 分别为当前与最大半径（m）；$\dot R,\ddot R$ 为速度（m s⁻¹）与加速度（m s⁻²）；$\rho>0$ 为载液密度（kg m⁻³）。",
    "Idealized collapse initial-value problem", "sphere", ["Rmax at t = 0", "Ṙ(0) = 0", "R(t)", "R̈", "p∞", "pv", "Δpc > 0", "ρ"], ["Constant pressure deficit initiates inward acceleration"], "The ideal control begins at rest and excludes the mechanisms that arrest real collapse.", "理想对照从静止开始，并排除了阻止实际塌缩的机制。")
body += P("<strong>Step 11 — Change the independent variable only on the collapse branch.</strong> Initial acceleration is negative, so radius decreases for the interior of this branch. Define squared speed as a function of radius. Away from the turning point, use the chain rule and cancel the nonzero speed; extend the resulting relation continuously back to the initial endpoint. Multiply the first-order equation by radius cubed to form an exact derivative.",
    "<strong>步骤 11——仅在塌缩分支上改变自变量。</strong> 初始加速度为负，因此半径在这一分支内部递减。把速度平方定义为半径函数。在转折点之外使用链式法则，并约去非零速度；随后通过连续延拓把关系带回初始端点。将一阶方程乘以半径三次方，形成完整导数。")
body += eq("C1-E14", r"\begin{aligned}y(R)&=\dot R^2,\qquad \frac{dy}{dt}=\frac{dy}{dR}\dot R=2\dot R\ddot R\quad\Longrightarrow\quad\ddot R=\frac12\frac{dy}{dR},\\\frac{dy}{dR}+\frac{3y}{R}&=-\frac{2\Delta p_c}{\rho R},\\\frac{d(R^3y)}{dR}&=R^3\frac{dy}{dR}+3R^2y=-\frac{2\Delta p_c}{\rho}R^2.\end{aligned}",
    r"$y(R)$ is squared wall speed (m² s⁻²); $R\in(0,R_{\max})$ is decreasing radius (m); $t$ is time (s); $\dot R\ne0$ and $\ddot R$ are speed (m s⁻¹) and acceleration (m s⁻²); $\Delta p_c$ is positive pressure difference (Pa); $\rho$ is carrier density (kg m⁻³); $d/dR$ and $d/dt$ are ordinary derivatives on the monotonic branch. Radius powers are the integrating factor, not derivatives.",
    r"$y(R)$ 为壁面速度平方（m² s⁻²）；$R\in(0,R_{\max})$ 为递减半径（m）；$t$ 为时间（s）；$\dot R\ne0$ 与 $\ddot R$ 为速度（m s⁻¹）与加速度（m s⁻²）；$\Delta p_c$ 为正压差（Pa）；$\rho$ 为载液密度（kg m⁻³）；$d/dR$ 与 $d/dt$ 为单调分支上的普通导数。半径幂构成积分因子，并非导数。",
    "Exact chain rule and integrating factor", "sphere", ["y(R) = Ṙ²", "R decreases", "Ṙ ≠ 0", "R̈", "Δpc", "ρ", "R³y", "t", "Rmax endpoint"], ["Cancel speed only away from the initial turning point"], "The monotonic collapse branch allows radius to replace time in the first integration.", "单调塌缩分支允许在第一次积分中以半径取代时间。")
body += eq("C1-E15", r"\begin{aligned}R^3y(R)-R_{\max}^3y(R_{\max})&=-\frac{2\Delta p_c}{\rho}\int_{R_{\max}}^R s^2\,ds=-\frac{2\Delta p_c}{3\rho}(R^3-R_{\max}^3),\\y(R_{\max})&=0,\qquad \dot R=-\sqrt{\frac{2\Delta p_c}{3\rho}\left[\left(\frac{R_{\max}}{R}\right)^3-1\right]}.\end{aligned}",
    r"$R\in(0,R_{\max}]$ and $R_{\max}$ are current and maximum radii (m); $y$ is squared speed (m² s⁻²); $s$ is dummy radius (m); $\Delta p_c>0$ is collapse pressure (Pa); $\rho>0$ is carrier density (kg m⁻³); $\dot R\le0$ is inward wall velocity (m s⁻¹). The square root denotes the nonnegative root; its prefixed minus sign selects collapse.",
    r"$R\in(0,R_{\max}]$ 与 $R_{\max}$ 分别为当前与最大半径（m）；$y$ 为速度平方（m² s⁻²）；$s$ 为积分哑半径（m）；$\Delta p_c>0$ 为塌缩压差（Pa）；$\rho>0$ 为载液密度（kg m⁻³）；$\dot R\le0$ 为向内壁面速度（m s⁻¹）。根号表示非负平方根；前置负号选择塌缩分支。",
    "Integrated speed with initial constant and branch", "sphere", ["Rmax", "R", "s: integration radius", "y = Ṙ²", "Ṙ < 0", "Δpc", "ρ"], ["Speed is zero at R = Rmax", "Zero radius is an excluded model endpoint"], "The initial condition fixes the integration constant and the inward sign fixes the branch.", "初值确定积分常数，向内的符号确定解分支。")
body += P("<strong>Step 12 — Separate dimensions from the dimensionless trajectory.</strong> Integrate reciprocal inward speed from maximum radius to zero. Change radius to a fraction of maximum radius. The same positive dimensionless integral applies to every member of this ideal family, which proves the proportionality rather than merely guessing it from units.",
    "<strong>步骤 12——将量纲尺度与无量纲轨迹分离。</strong> 从最大半径至零积分向内速度的倒数，再把半径换成最大半径的比例。该理想模型族中的所有情形具有相同的正无量纲积分，因此得到的是比例关系的证明，而不只是量纲猜测。")
body += eq("C1-E16", r"\begin{aligned}t_c&=\int_{R_{\max}}^0\frac{dR}{\dot R}=\sqrt{\frac{3\rho}{2\Delta p_c}}\int_0^{R_{\max}}\frac{dR}{\sqrt{(R_{\max}/R)^3-1}},\\x&=\frac{R}{R_{\max}},\qquad dR=R_{\max}dx,\\t_c&=R_{\max}\sqrt{\frac{\rho}{\Delta p_c}}\ C_t,\qquad C_t=\sqrt{\frac32}\int_0^1\frac{x^{3/2}}{\sqrt{1-x^3}}\,dx.\end{aligned}",
    r"$t_c$ is ideal collapse time (s); $R$ is radius and $R_{\max}$ its maximum (m); $\dot R<0$ is inward velocity (m s⁻¹); $\rho$ is density (kg m⁻³); $\Delta p_c>0$ is pressure difference (Pa); $x=R/R_{\max}\in[0,1]$ is dimensionless radius; $C_t$ is the dimensionless time coefficient; definite integrals follow the collapse branch. $dx$ and $dR$ denote integration measures.",
    r"$t_c$ 为理想塌缩时间（s）；$R$ 为半径，$R_{\max}$ 为其最大值（m）；$\dot R<0$ 为向内速度（m s⁻¹）；$\rho$ 为密度（kg m⁻³）；$\Delta p_c>0$ 为压差（Pa）；$x=R/R_{\max}\in[0,1]$ 为无量纲半径；$C_t$ 为无量纲时间系数；定积分沿塌缩分支进行。$dx$ 与 $dR$ 表示积分测度。",
    "Exact separation and nondimensionalization", "timescale", ["tc", "Rmax", "R", "Ṙ < 0", "ρ", "Δpc", "x = R/Rmax", "Ct"], ["At x = 0 the integrand behaves as x³ᐟ²", "At x = 1 it behaves as (1 − x)⁻¹ᐟ²"], "The endpoint singularity is integrable, so the model has a finite collapse time.", "端点奇异性可积，因此该模型具有有限塌缩时间。")
body += P("<strong>Step 13 — Evaluate the coefficient, including the Jacobian.</strong> Set the new integration variable equal to the cube of normalized radius. The radius power contributes a factor with exponent one half, and the Jacobian contributes exponent minus two thirds; their sum is minus one sixth. Recognize the beta integral. Both beta arguments are positive, establishing convergence. This derived coefficient agrees with the published Rayleigh factor. "+cite("r1")+" "+cite("r3"),
    "<strong>步骤 13——连同雅可比因子一起求出系数。</strong> 令新积分变量为无量纲半径的三次方。半径幂贡献二分之一的指数，雅可比因子贡献负三分之二的指数；相加得到负六分之一。将其识别为贝塔积分。两个贝塔参数均为正，保证积分收敛。推导所得系数与文献中的瑞利因子一致。 "+cite("r1")+" "+cite("r3"))
body += eq("C1-E17", r"\begin{aligned}q&=x^3,\quad x=q^{1/3},\quad dx=\frac13q^{-2/3}\,dq,\\C_t&=\frac{1}{\sqrt6}\int_0^1q^{-1/6}(1-q)^{-1/2}\,dq=\frac{1}{\sqrt6}B\left(\frac56,\frac12\right)=0.9146813565\ldots,\\B(a,b)&=\int_0^1q^{a-1}(1-q)^{b-1}\,dq\quad(a>0,b>0).\end{aligned}",
    r"$x$ and $q=x^3$ are dimensionless radius and substitution variables on [0,1]; $C_t$ is the dimensionless collapse-time coefficient; $B(a,b)$ is the beta function, defined by the displayed convergent integral; $a,b$ are positive dimensionless arguments; $dx,dq$ are integration measures. The numeral 6 inside the root is a dimensionless constant; the ellipsis indicates decimal continuation.",
    r"$x$ 与 $q=x^3$ 分别为区间 [0,1] 上的无量纲半径与换元变量；$C_t$ 为无量纲塌缩时间系数；$B(a,b)$ 为贝塔函数，由公式中的收敛积分定义；$a,b$ 为正的无量纲参数；$dx,dq$ 为积分测度。根号中的数字 6 为无量纲常数；省略号表示后续小数。",
    "Evaluated beta-function coefficient", "timescale", ["x ∈ [0,1]", "q = x³", "dx = q⁻²ᐟ³dq/3", "Ct = 0.914681…", "B(a,b)", "a = 5/6", "b = 1/2"], ["The coefficient comes from the complete radius trajectory, not a material fit"], "The change of variables exposes the beta integral that fixes the numerical coefficient.", "换元揭示贝塔积分，从而确定数值系数。")
body += P("<strong>Step 14 — Check energy against the integrated trajectory.</strong> Substitute squared speed from Eq. (C1-E15) into the kinetic-energy integral. The result equals the pressure work done as cavity volume is lost. Zero speed at maximum radius gives zero kinetic energy there, while decreasing radius gives positive energy. This independently verifies the sign and integration constant.",
    "<strong>步骤 14——用积分轨迹检验能量。</strong> 将式（C1-E15）的速度平方代入动能积分。结果等于空腔体积减少时的压力功。最大半径处速度为零，因此动能为零；半径减小时，动能为正。这独立检验了符号与积分常数。")
body += eq("C1-E18", r"\begin{aligned}K_l(R)&=2\pi\rho R^3\frac{2\Delta p_c}{3\rho}\left[\left(\frac{R_{\max}}R\right)^3-1\right]=\frac{4\pi}{3}\Delta p_c(R_{\max}^3-R^3),\\E_B&=\Delta p_cV_{\max}=\frac{4\pi}{3}\Delta p_cR_{\max}^3,\qquad \frac{K_l}{E_B}=1-\left(\frac R{R_{\max}}\right)^3.\end{aligned}",
    r"$K_l$ is carrier kinetic energy, $E_B$ the maximum-volume pressure-work scale (J); $R\in(0,R_{\max}]$ and $R_{\max}$ are radii (m); $\rho$ is density (kg m⁻³); $\Delta p_c$ is constant positive pressure difference (Pa); $V_{\max}$ is maximum cavity volume (m³); $\pi$ is the circle constant. $K_l/E_B$ is dimensionless and this control has zero viscous and capillary losses.",
    r"$K_l$ 为载液动能，$E_B$ 为最大体积的压力功尺度（J）；$R\in(0,R_{\max}]$ 与 $R_{\max}$ 为半径（m）；$\rho$ 为密度（kg m⁻³）；$\Delta p_c$ 为常数正压差（Pa）；$V_{\max}$ 为最大空腔体积（m³）；$\pi$ 为圆周率。$K_l/E_B$ 无量纲，此对照模型的黏性与毛细损失为零。",
    "Independent pressure-work conservation check", "energy", ["Kl(R)", "EB", "Δpc", "Vmax", "Rmax", "R", "ρ", "Kl/EB = 1 − (R/Rmax)³"], ["Finite energy survives the excluded zero-radius speed singularity"], "The Rayleigh speed solution and pressure-work balance agree exactly.", "瑞利速度解与压力功平衡严格一致。")

body += H("Worked control: a 30 μm cavity", "已解对照：30 μm 空腔", "worked-control", 3)
body += P("Use the supplied source's teaching inputs: maximum radius 30 μm, carrier density 1000 kg m⁻³, and collapse pressure 100 kPa. These are declared model inputs, not measured PFC properties. Substitute SI values before converting the outputs. At half radius, the cubic ratio is eight; subtracting one gives seven.",
    "采用所提供文件的教学输入：最大半径 30 μm、载液密度 1000 kg m⁻³、塌缩压差 100 kPa。这些为声明的模型输入，并非 PFC 实测物性。先代入 SI 数值，再换算输出单位。在一半半径处，三次方比值为八；减去一后得到七。")
body += eq("C1-E19", r"\begin{aligned}t_c&=0.9146813565(30\times10^{-6})\sqrt{\frac{1000}{100\times10^3}}\ \mathrm s=2.74404\ \mu\mathrm s,\\E_B&=\frac{4\pi}{3}(100\times10^3)(30\times10^{-6})^3\ \mathrm J=11.3097\ \mathrm{nJ},\\\dot R\big|_{R=R_{\max}/2}&=-\sqrt{\frac{2(100\times10^3)}{3(1000)}(8-1)}\ \mathrm{m\,s^{-1}}=-21.6025\ \mathrm{m\,s^{-1}},\\K_l\big|_{R=R_{\max}/2}&=\frac78E_B=9.89602\ \mathrm{nJ}.\end{aligned}",
    r"$t_c$ is collapse time (s), $E_B$ pressure-work scale (J), $K_l$ carrier kinetic energy (J), $R$ current radius and $R_{\max}=30\times10^{-6}$ m maximum radius; $\dot R$ is signed wall speed (m s⁻¹). Substituted inputs are $\rho=1000$ kg m⁻³ and $\Delta p_c=100\times10^3$ Pa. $\pi$ is the circle constant; s, J, μs and nJ mean seconds, joules, microseconds and nanojoules; the vertical bar specifies half-radius evaluation.",
    r"$t_c$ 为塌缩时间（s），$E_B$ 为压力功尺度（J），$K_l$ 为载液动能（J），$R$ 为当前半径，$R_{\max}=30\times10^{-6}$ m 为最大半径；$\dot R$ 为带符号壁面速度（m s⁻¹）。代入输入为 $\rho=1000$ kg m⁻³ 与 $\Delta p_c=100\times10^3$ Pa。$\pi$ 为圆周率；s、J、μs 与 nJ 分别为秒、焦耳、微秒与纳焦耳；竖线表示在一半半径处取值。",
    "Declared teaching calculation", "sphere", ["Rmax = 30 μm", "R = 15 μm", "ρ = 1000 kg/m³", "Δpc = 100 kPa", "tc = 2.74404 μs", "EB = 11.3097 nJ", "Ṙ = −21.6025 m/s", "Kl = 9.89602 nJ"], ["These values are a spherical control, not a PFC performance prediction"], "The original numerical control is preserved with its energy and branch checks.", "保留原始数值对照，并补充能量与解分支检验。")
body += P("The time scale has units of length times the square root of density divided by pressure, hence seconds. Doubling radius doubles time and multiplies the work scale by eight. Multiplying pressure difference by four halves time and doubles wall-speed magnitude at a fixed radius fraction; the coefficient remains unchanged because the dimensionless initial-value problem is unchanged. Gas cushioning, changing vapor pressure or confinement can change that problem and therefore its coefficient.",
    "时间尺度的量纲为长度乘密度与压力之比的平方根，因此单位为秒。半径加倍使时间加倍，并使压力功尺度增至八倍。压差增至四倍使时间减半，并使固定半径比例处的壁面速率加倍；系数不变，是因为无量纲初值问题没有改变。气体缓冲、变化蒸气压或约束会改变该问题，因此也可能改变其系数。")
body += P("As radius approaches zero, this model concentrates a finite energy into a shrinking moving-liquid scale and predicts unbounded wall speed. It does not prove unbounded physical velocity or a jet at all. Compressibility, internal pressure, thermal and mass transfer, molecular scales and loss of symmetry intervene. The next equation locates only where a selected Mach diagnostic is crossed in the ideal trajectory; it is neither an arrest law nor a maximum-speed prediction.",
    "半径趋于零时，此模型把有限能量集中到不断缩小的运动液体尺度中，预测无界壁面速度。它既不能证明实际速度无界，也不能证明一定形成射流。可压缩性、内部压力、传热传质、分子尺度及对称性破坏都会介入。下一式仅定位理想轨迹越过所选马赫数诊断值的位置；它既不是终止塌缩定律，也不是最大速度预测。")
body += eq("C1-E20", r"M_w=\frac{|\dot R|}{c},\qquad x_M=\left[1+\frac{3\rho c^2M_*^2}{2\Delta p_c}\right]^{-1/3},\qquad M_*=0.1,\ c=1500\ \mathrm{m\,s^{-1}}\ \Longrightarrow\ x_M=0.143487",
    r"$M_w$ is wall Mach number (dimensionless); $\dot R$ is wall speed (m s⁻¹); absolute bars denote magnitude; $c>0$ is stipulated carrier sound speed (m s⁻¹); $M_*>0$ is a selected diagnostic Mach value; $x_M=R_M/R_{\max}$ is the radius fraction when $M_w=M_*$; $R_M,R_{\max}$ are radii (m); $\rho$ is carrier density (kg m⁻³); $\Delta p_c$ is positive collapse pressure (Pa). The number uses the previous teaching density and pressure.",
    r"$M_w$ 为壁面马赫数（无量纲）；$\dot R$ 为壁面速度（m s⁻¹）；绝对值符号表示大小；$c>0$ 为给定载液声速（m s⁻¹）；$M_*>0$ 为选择的诊断马赫值；$x_M=R_M/R_{\max}$ 为 $M_w=M_*$ 时的半径比例；$R_M,R_{\max}$ 为半径（m）；$\rho$ 为载液密度（kg m⁻³）；$\Delta p_c$ 为正塌缩压差（Pa）。数值使用前述教学密度与压差。",
    "Ideal-trajectory diagnostic, not a physical limit", "timescale", ["Mw = |Ṙ|/c", "Ṙ", "c = 1500 m/s", "M* = 0.1", "xM = RM/Rmax", "ρ", "Δpc", "RM ≈ 4.305 μm"], ["The selected threshold flags omitted physics; it does not stop a real cavity"], "A Mach diagnostic exposes the shrinking validity range of incompressible collapse.", "马赫数诊断揭示不可压缩塌缩模型的适用范围不断缩小。")

body += H("1.6 Derive pressure impulse and locate directionality", "1.6 推导压力冲量并定位方向性来源", "pressure-impulse")
body += P("<strong>Step 15 — Define a field, not a pressure peak.</strong> Pressure impulse is the time integral of local pressure relative to a spatially uniform reference. It is impulse per area, with units Pa s. Its spatial gradient will drive liquid acceleration. It must never be equated to the acoustic crossing time, which has units of seconds. The pressure-impulse literature motivates this short-event reduction; the following integration exposes its omitted terms. "+cite("r2"),
    "<strong>步骤 15——定义空间场，而非压力峰值。</strong> 压力冲量是局部压力相对于空间均匀参考值的时间积分，属于单位面积上的冲量，单位为 Pa s。其空间梯度驱动液体加速。绝不能把它等同于单位为秒的声传播时间。压力冲量文献支持这一短事件约化；以下积分明确展示所忽略的项。 "+cite("r2"))
body += eq("C1-E21", r"\Pi(\boldsymbol x)=\int_{t_0}^{t_1}\left[p(\boldsymbol x,t)-p_{\mathrm{ref}}(t)\right]dt,\qquad \tau=t_1-t_0>0,\qquad [\Pi]=\mathrm{Pa\,s}",
    r"$\boldsymbol x$ is fixed liquid position (m); $\Pi$ is pressure impulse (Pa s); $p$ is local pressure and $p_{\mathrm{ref}}$ a spatially uniform reference (Pa); $t$ is time and $t_0,t_1$ event endpoints (s); $\tau$ is event duration (s). Square brackets on $\Pi$ denote units, not endpoint evaluation. The integral is at fixed position in a liquid domain whose displacement will be assessed below.",
    r"$\boldsymbol x$ 为固定液体位置（m）；$\Pi$ 为压力冲量（Pa s）；$p$ 为局部压力，$p_{\mathrm{ref}}$ 为空间均匀参考压力（Pa）；$t$ 为时间，$t_0,t_1$ 为事件端点（s）；$\tau$ 为持续时间（s）。$\Pi$ 的方括号表示单位，而非端点取值。积分在固定位置进行，液体区域的位移将在下文评估。",
    "Definition of local pressure impulse", "impulse", ["Π(x)", "p(x,t) − pref(t)", "x: position", "t₀", "t₁", "τ = t₁ − t₀", "Pa s"], ["Shade the time integral of pressure at a selected position"], "Impulse combines duration and amplitude at each liquid position.", "压力冲量在每个液体位置组合压力幅值与持续时间。")
body += eq("C1-E22", r"\Delta\boldsymbol u=-\frac{\nabla\Pi}{\rho}-\int_{t_0}^{t_1}(\boldsymbol u\cdot\nabla)\boldsymbol u\,dt+\nu\int_{t_0}^{t_1}\nabla^2\boldsymbol u\,dt,\qquad \Delta\boldsymbol u=\boldsymbol u(\boldsymbol x,t_1)-\boldsymbol u(\boldsymbol x,t_0),\quad \nu=\frac\mu\rho",
    r"$\Delta\boldsymbol u$ is fixed-position velocity change and $\boldsymbol u$ velocity (m s⁻¹); $\Pi$ is pressure impulse (Pa s); $\rho$ is constant density (kg m⁻³); $\mu$ is viscosity (Pa s); $\nu$ is kinematic viscosity (m² s⁻¹); $t_0,t_1,t$ are times (s); $\boldsymbol x$ is fixed position (m); $\nabla$ is spatial gradient (m⁻¹), $\nabla^2$ the vector Laplacian (m⁻²); the dot is a true vector contraction in convective acceleration, not an equation separator.",
    r"$\Delta\boldsymbol u$ 为固定位置速度变化，$\boldsymbol u$ 为速度（m s⁻¹）；$\Pi$ 为压力冲量（Pa s）；$\rho$ 为常数密度（kg m⁻³）；$\mu$ 为黏度（Pa s）；$\nu$ 为运动黏度（m² s⁻¹）；$t_0,t_1,t$ 为时间（s）；$\boldsymbol x$ 为固定位置（m）；$\nabla$ 为空间梯度（m⁻¹），$\nabla^2$ 为矢量拉普拉斯（m⁻²）；圆点是对流加速度中的真正矢量缩并，并非公式分隔符。",
    "Exact fixed-position integrated incompressible momentum", "impulse", ["Δu", "−∇Π/ρ", "u(x,t)", "ρ", "μ", "ν = μ/ρ", "t₀ → t₁", "Convective impulse", "Viscous impulse"], ["Pressure-gradient impulse shares momentum change with two residual terms"], "The short-event approximation must justify removing convective and viscous impulses.", "短事件近似必须说明为何可以删除对流与黏性冲量。")
body += P("<strong>Step 16 — Declare the small-event conditions before discarding terms.</strong> Choose a liquid speed and variation length. Convective and viscous impulses relative to that speed scale respectively with speed times duration divided by length, and kinematic viscosity times duration divided by length squared. Small interface displacement is also required to freeze the boundary geometry. These are scaling diagnostics, not guaranteed error bounds in a singular boundary layer. Under those conditions, subtract incompressible velocities and take the divergence.",
    "<strong>步骤 16——删项之前先声明小事件条件。</strong> 选取液体速度与变化长度。对流和黏性冲量相对于该速度的尺度，分别为速度乘持续时间除以长度、以及运动黏度乘持续时间除以长度平方。冻结边界几何还要求界面位移足够小。这些是尺度诊断，并非奇异边界层中的严格误差上界。在这些条件下，将两个不可压缩速度场相减，再取散度。")
body += eq("C1-E23", r"\frac{U\tau}{L}\ll1,\qquad \frac{\nu\tau}{L^2}\ll1,\qquad \Delta\boldsymbol u\simeq-\frac{\nabla\Pi}{\rho},\qquad 0=\nabla\cdot\Delta\boldsymbol u\simeq-\frac{\nabla^2\Pi}{\rho}\ \Longrightarrow\ \nabla^2\Pi=0",
    r"$U>0$ is a characteristic liquid speed (m s⁻¹); $\tau$ is impulse duration (s); $L>0$ is liquid variation length (m); $\nu$ is kinematic viscosity (m² s⁻¹); $\Delta\boldsymbol u$ is velocity change (m s⁻¹); $\Pi$ is pressure impulse (Pa s); $\rho$ is density (kg m⁻³); $\nabla\cdot$ denotes divergence and $\nabla^2$ Laplacian; $\ll$ means asymptotically small, and $\simeq$ marks the reduced approximation. The last Laplace equation belongs to that reduced model.",
    r"$U>0$ 为特征液体速度（m s⁻¹）；$\tau$ 为冲量持续时间（s）；$L>0$ 为液体变化长度（m）；$\nu$ 为运动黏度（m² s⁻¹）；$\Delta\boldsymbol u$ 为速度变化（m s⁻¹）；$\Pi$ 为压力冲量（Pa s）；$\rho$ 为密度（kg m⁻³）；$\nabla\cdot$ 表示散度，$\nabla^2$ 表示拉普拉斯算子；$\ll$ 表示渐近很小，$\simeq$ 表示约化近似。最后的拉普拉斯方程属于该约化模型。",
    "Short-event reduced pressure-impulse model", "impulse", ["U", "τ", "L", "ν", "Π(x)", "Δu ≈ −∇Π/ρ", "∇²Π = 0", "ρ"], ["Freeze the domain only while displacement and residual impulses remain small"], "The velocity depends on a spatial impulse gradient constrained by boundary geometry.", "速度取决于受边界几何约束的空间压力冲量梯度。")
body += P("A fixed impermeable wall imposes zero normal velocity change and hence zero normal impulse derivative. A driven cavity supplies a prescribed impulse or a pressure history; a freely communicating outlet supplies its own pressure reference. These are different boundary data. Adding a spatially uniform impulse changes no velocity because its gradient vanishes. The same pressure maximum, acting for a different duration or over a different geometry, can therefore produce a different velocity field.",
    "固定不可穿透壁面要求法向速度变化为零，因此法向压力冲量导数为零。受驱动空腔提供给定冲量或压力历程；自由连通的出口提供相应压力参考。这些是不同的边界数据。空间均匀增加压力冲量不会改变速度，因为其梯度为零。因此，同一个压力峰值在不同持续时间或不同几何中，可以产生不同速度场。")
body += P("<strong>Step 17 — Solve a straight-column benchmark completely.</strong> Use an initially stationary uniform liquid column along a positive axial coordinate, with constant area, fixed side walls, prescribed positive impulse at its driven end and zero at its outlet. The one-dimensional Laplace equation integrates twice. Apply both endpoint values rather than assuming a uniform gradient.",
    "<strong>步骤 17——完整解出直液柱基准。</strong> 考虑沿正轴向坐标的初始静止均匀液柱，其面积恒定、侧壁固定，受驱动端压力冲量给定为正、出口为零。一维拉普拉斯方程积分两次。应用两个端点条件，而不是直接假定均匀梯度。")
body += eq("C1-E24", r"\begin{aligned}\frac{d^2\Pi}{dz^2}&=0\quad\Longrightarrow\quad\Pi=A_1z+A_0,\\\Pi(0)&=\Pi_0,\quad\Pi(L)=0\quad\Longrightarrow\quad A_0=\Pi_0,\quad A_1=-\frac{\Pi_0}{L},\\\Pi(z)&=\Pi_0\left(1-\frac zL\right),\qquad \Delta u_z=-\frac1\rho\frac{d\Pi}{dz}=\frac{\Pi_0}{\rho L}.\end{aligned}",
    r"$z\in[0,L]$ is axial position and $L>0$ column length (m); $\Pi(z)$ and $\Pi_0>0$ are local and driven-end impulses (Pa s); $A_0$ is an integration constant (Pa s), $A_1$ a gradient constant (Pa s m⁻¹); $\rho>0$ is carrier density (kg m⁻³); $\Delta u_z$ is positive axial speed change (m s⁻¹); $d/dz$ is an axial derivative. Subscript $z$ labels the component and 0 the driven endpoint.",
    r"$z\in[0,L]$ 为轴向位置，$L>0$ 为液柱长度（m）；$\Pi(z)$ 与 $\Pi_0>0$ 为局部与受驱动端冲量（Pa s）；$A_0$ 为积分常数（Pa s），$A_1$ 为梯度常数（Pa s m⁻¹）；$\rho>0$ 为载液密度（kg m⁻³）；$\Delta u_z$ 为正轴向速度变化（m s⁻¹）；$d/dz$ 为轴向导数。下标 $z$ 表示分量，0 表示受驱动端点。",
    "Exact straight-column solution of the reduced model", "impulse", ["z = 0: Π₀", "z = L: Π = 0", "L", "Π(z)", "A₀ = Π₀", "A₁ = −Π₀/L", "ρ", "Δuz → outlet"], ["The fixed side walls do not change normal velocity"], "A linear spatial impulse drop accelerates liquid toward the outlet.", "线性的空间冲量下降使液体向出口加速。")
body += P("For a second declared teaching control, impose 0.60 MPa for 0.50 μs across a 100 μm column, with the earlier carrier density and stipulated viscosity 0.001 Pa s and sound speed 1500 m s⁻¹. The speed change is 3.0 m s⁻¹. The crossing time is much shorter than the pulse, but that fact does not prove uniform pressure, correct boundary data, or a final jet speed. The solved column has an end-to-end pressure gradient, not spatially equal pressure.",
    "第二个声明的教学对照：在 100 μm 液柱两端施加 0.60 MPa 压差，持续 0.50 μs，采用前述载液密度，并给定黏度 0.001 Pa s、声速 1500 m s⁻¹。速度变化为 3.0 m s⁻¹。声传播时间远短于脉冲，但这不能证明空间压力均匀、边界数据正确或已经得到最终射流速度。解出的液柱具有端到端压力梯度，而非空间处处相同的压力。")
body += eq("C1-E25", r"\begin{aligned}\Pi_0&=\Delta p\tau=(0.60\times10^6)(0.50\times10^{-6})\ \mathrm{Pa\,s}=0.30\ \mathrm{Pa\,s},\\U&=\frac{\Pi_0}{\rho L}=3.0\ \mathrm{m\,s^{-1}},\qquad t_a=\frac Lc=0.066667\ \mu\mathrm s,\\\frac{U\tau}{L}&=0.015,\qquad\frac{\nu\tau}{L^2}=5.0\times10^{-5},\qquad\frac{\tau}{t_a}=7.5.\end{aligned}",
    r"$\Pi_0$ is driven-end impulse (Pa s); $\Delta p$ is constant applied column pressure difference (Pa); $\tau$ is pulse duration (s); $U$ is column speed increment (m s⁻¹); $\rho=1000$ kg m⁻³ is density; $L=100\times10^{-6}$ m is length; $c=1500$ m s⁻¹ is sound speed; $t_a$ is acoustic crossing time (s); $\nu=\mu/\rho=10^{-6}$ m² s⁻¹ with $\mu=0.001$ Pa s. The three ratios are dimensionless; μs means microseconds.",
    r"$\Pi_0$ 为受驱动端冲量（Pa s）；$\Delta p$ 为施加的常数液柱压差（Pa）；$\tau$ 为脉冲持续时间（s）；$U$ 为液柱速度增量（m s⁻¹）；$\rho=1000$ kg m⁻³ 为密度；$L=100\times10^{-6}$ m 为长度；$c=1500$ m s⁻¹ 为声速；$t_a$ 为声传播时间（s）；$\nu=\mu/\rho=10^{-6}$ m² s⁻¹，且 $\mu=0.001$ Pa s。三个比值均无量纲；μs 表示微秒。",
    "Declared impulse calculation and applicability diagnostics", "impulse", ["Δp = 0.60 MPa", "τ = 0.50 μs", "Π₀ = 0.30 Pa s", "ρ", "L = 100 μm", "U = 3.0 m/s", "c", "ta = L/c", "ν"], ["Small bulk residual scales support the ideal column approximation", "Many sound crossings are not a guarantee of correct pressure geometry"], "Pressure impulse and acoustic time have distinct definitions, dimensions and roles.", "压力冲量与声传播时间具有不同的定义、量纲与作用。")
body += P("Direction enters through asymmetry. A sphere in an infinite uniform liquid produces radial inflow or outflow with zero net preferred direction. An outlet, meniscus curvature, rigid or compliant wall, neighboring cavity, or nonuniform heating breaks that symmetry. Define stand-off as center-to-boundary distance normalized by maximum radius. Boundary curvature and material response remain additional parameters even when stand-off matches. A rigid plane commonly attracts a collapse jet toward it; deformable surfaces can alter or split the response. "+cite("r3")+" "+cite("r12"),
    "方向性来自非对称性。无限均匀液体中的球形空腔产生径向流入或流出，但没有净优选方向。出口、弯月面曲率、刚性或柔顺壁面、邻近空腔、非均匀加热都能破坏对称性。离壁比定义为中心到边界的距离除以最大半径。即使离壁比相同，边界曲率与材料响应仍是额外参数。刚性平面通常使塌缩射流指向壁面；可变形表面能够改变或分裂响应。 "+cite("r3")+" "+cite("r12"))
body += eq("C1-E26", r"\gamma=\frac h{R_{\max}},\qquad \int_{S^2}\boldsymbol e_r\,d\Omega=\boldsymbol0",
    r"$\gamma$ is dimensionless stand-off; $h$ is bubble-center-to-boundary distance (m); $R_{\max}$ is maximum radius (m); $S^2$ denotes all directions on the unit sphere; $\boldsymbol e_r$ is the outward radial unit vector; $d\Omega$ is the dimensionless solid-angle measure; $\boldsymbol0$ is the zero vector. The angular identity expresses directional cancellation under perfect spherical symmetry; it is not a boundary-jet prediction.",
    r"$\gamma$ 为无量纲离壁比；$h$ 为气泡中心到边界的距离（m）；$R_{\max}$ 为最大半径（m）；$S^2$ 表示单位球面上的全部方向；$\boldsymbol e_r$ 为向外径向单位矢量；$d\Omega$ 为无量纲立体角测度；$\boldsymbol0$ 为零矢量。角积分恒等式表示完全球对称下方向相互抵消，并非边界射流预测。",
    "Geometry definition and exact symmetry identity", "sphere", ["h: center to boundary", "Rmax", "γ = h/Rmax", "er", "S²", "dΩ", "Opposite directions cancel"], ["The relevant boundary type and curvature must also be specified"], "Stand-off locates a boundary; perfect spherical symmetry selects no outgoing direction.", "离壁比定位边界；完全球对称不能选出向外喷射方向。")

body += H("1.7 Close a spatial moving-interface problem", "1.7 闭合空间运动界面问题", "spatial-closure")
body += P("<strong>Step 18 — Restore the degrees of freedom that a jet needs.</strong> To predict jet direction, diameter and time-dependent velocity, specify the initial interface shape and carrier velocity, actual solid boundaries, outlet and contact-line behavior, and a pressure closure. The bulk conservation equations below are exact for an incompressible Newtonian carrier with constant properties and omitted gravity. Their solution requires the interface and boundary conditions that follow, and cannot be replaced by a fitted radius history alone.",
    "<strong>步骤 18——恢复射流所需的自由度。</strong> 预测射流方向、直径与随时间变化的速度，需要给定初始界面形状和载液速度、实际固体边界、出口与接触线行为，以及压力闭合关系。以下体内守恒方程对物性恒定、忽略重力的不可压缩牛顿载液是精确的。求解需要后续界面与边界条件，不能仅用拟合的半径历程取代。")
body += eq("C1-E27", r"\nabla\cdot\boldsymbol u=0,\qquad \rho\left(\frac{\partial\boldsymbol u}{\partial t}+(\boldsymbol u\cdot\nabla)\boldsymbol u\right)=-\nabla p+\mu\nabla^2\boldsymbol u",
    r"$\boldsymbol u(\boldsymbol x,t)$ is liquid velocity (m s⁻¹); $\boldsymbol x$ is spatial position (m); $t$ is time (s); $\rho$ is constant carrier density (kg m⁻³); $p$ is liquid pressure (Pa); $\mu$ is constant viscosity (Pa s); $\nabla\cdot,\nabla,\nabla^2$ denote divergence, gradient and vector Laplacian; $\partial_t$ is the fixed-position derivative. The dot in convection is vector contraction. The momentum equation has force-per-volume units (N m⁻³).",
    r"$\boldsymbol u(\boldsymbol x,t)$ 为液体速度（m s⁻¹）；$\boldsymbol x$ 为空间位置（m）；$t$ 为时间（s）；$\rho$ 为常数载液密度（kg m⁻³）；$p$ 为液体压力（Pa）；$\mu$ 为常数黏度（Pa s）；$\nabla\cdot,\nabla,\nabla^2$ 分别为散度、梯度与矢量拉普拉斯；$\partial_t$ 为固定位置导数。对流中的圆点为矢量缩并。动量方程各项单位为单位体积力（N m⁻³）。",
    "Bulk conservation and Newtonian constitutive assumption", "jet", ["Liquid domain x", "u(x,t)", "p(x,t)", "ρ", "μ", "t", "Moving Γ", "Outlet and wall"], ["Resolve the spatial velocity and pressure, not only one radius"], "Bulk momentum and volume conservation supply the spatial field needed for jet formation.", "体内动量与体积守恒给出射流形成所需的空间场。")
body += P("<strong>Step 19 — State the interface orientation and stress before using curvature.</strong> The interface normal now points from the liquid into the gas. Therefore an inner spherical cavity has negative curvature, while an outer liquid droplet has positive curvature. This convention reproduces the spherical stress in Eq. (C1-E06). For a clean interface and negligible gas viscous stress, tangential viscous traction vanishes. Retain the viscosity factor: at zero viscosity this condition imposes no additional strain-rate constraint. With no phase transfer, the interface normal velocity equals the carrier normal velocity.",
    "<strong>步骤 19——使用曲率之前先声明界面方向与应力。</strong> 此处界面法向由液体指向气体。因此，内部球形空腔的曲率为负，外部液滴曲率为正。这一约定能够恢复式（C1-E06）的球形应力。对洁净界面且气相黏性应力可忽略时，切向黏性牵引力为零。保留黏度因子：黏度为零时，此条件不施加额外应变率约束。无相变传质时，界面法向速度等于载液法向速度。")
body += eq("C1-E28", r"\begin{aligned}\boldsymbol D&=\frac12\left(\nabla\boldsymbol u+(\nabla\boldsymbol u)^\mathsf T\right),\qquad \kappa=\nabla_s\cdot\boldsymbol n,\\V_n&=\boldsymbol u\cdot\boldsymbol n,\qquad p_l=p_b+\sigma\kappa+2\mu\boldsymbol n\cdot\boldsymbol D\boldsymbol n,\\2\mu\boldsymbol s\cdot\boldsymbol D\boldsymbol n&=0,\qquad \kappa_{\mathrm{sphere}}=-\frac2R.\end{aligned}",
    r"$\boldsymbol D$ is symmetric liquid strain-rate tensor (s⁻¹); $\boldsymbol u$ is velocity (m s⁻¹); $\nabla\boldsymbol u$ is its spatial gradient, with superscript $\mathsf T$ denoting transpose; $\boldsymbol n$ is the unit normal from liquid into gas; $\nabla_s\cdot$ is surface divergence; $\kappa$ is signed curvature (m⁻¹); $V_n$ is interface normal speed (m s⁻¹); $p_l,p_b$ are interface liquid and gas pressures (Pa); $\sigma$ is surface tension (N m⁻¹); $\mu$ is viscosity (Pa s); $\boldsymbol s$ is any unit tangent; $R$ is spherical cavity radius (m). Dots denote tensor/vector contractions.",
    r"$\boldsymbol D$ 为液体对称应变率张量（s⁻¹）；$\boldsymbol u$ 为速度（m s⁻¹）；$\nabla\boldsymbol u$ 为其空间梯度，上标 $\mathsf T$ 表示转置；$\boldsymbol n$ 为从液体指向气体的单位法向；$\nabla_s\cdot$ 为表面散度；$\kappa$ 为带符号曲率（m⁻¹）；$V_n$ 为界面法向速度（m s⁻¹）；$p_l,p_b$ 为界面液体与气体压力（Pa）；$\sigma$ 为表面张力（N m⁻¹）；$\mu$ 为黏度（Pa s）；$\boldsymbol s$ 为任意单位切向；$R$ 为球形空腔半径（m）。圆点表示张量或矢量缩并。",
    "Kinematic condition and clean-interface traction", "jet", ["Γ: liquid–gas interface", "n: liquid → gas", "s: tangent", "Vn = u·n", "u", "D", "pl", "pb", "σκ", "2μ n·D n", "κsphere = −2/R"], ["At a stationary no-slip solid wall use the wall velocity instead", "Phase transfer modifies the kinematic condition in Chapter 2"], "Interface normals, signed curvature and material motion must use one consistent convention.", "界面法向、带符号曲率与物质运动必须采用一致约定。")
body += P("At a stationary viscous solid wall, impose zero carrier velocity. At a moving film, its velocity and stress must be coupled to the liquid. At an outlet or free meniscus, prescribe the relevant external pressure and stress. A contact line needs an explicit pinned, moving-angle, or other physical closure; it is not determined by the bulk equations. Chapter 4 supplies the payload and release-interface mechanics. If phase transfer is appreciable, the no-slip-in-the-normal-direction condition must be replaced by the mass-flux balance derived in Chapter 2.",
    "在静止黏性固壁处，载液速度为零。在运动膜处，必须把膜的速度与应力同液体耦合。在出口或自由弯月面处，应给定相应外部压力与应力。接触线需要明确的钉扎、运动接触角或其他物理闭合关系；体内方程无法决定它。第四章补充载荷与释放界面的力学。若相变传质显著，必须将界面法向无速度滑移条件替换为第二章推导的质量通量平衡。")
body += P("<strong>Step 20 — Use a potential-flow reduction only with its additional assumptions.</strong> In an inviscid, initially irrotational carrier, away from shocks and unresolved wall layers, a velocity potential solves Laplace's equation. With no phase slip, material interface nodes follow the velocity. Distinguish the Eulerian Bernoulli derivative from the material derivative by adding velocity dotted with its own potential gradient. This gives a concrete pre-impact spatial closure rather than an equation for radius alone. Boundary-integral microjet calculations use this type of reduction. "+cite("r4"),
    "<strong>步骤 20——仅在额外假设成立时使用势流约化。</strong> 在无黏、初始无旋的载液中，远离激波及未解析壁面层时，速度势满足拉普拉斯方程。无相变滑移时，物质界面节点跟随速度运动。把速度与其自身速度势梯度的点积加入欧拉伯努利时间导数，即可区分欧拉导数与物质导数。这样得到的是撞击前的具体空间闭合关系，而非只有半径的方程。边界积分微射流研究采用这类约化。 "+cite("r4"))
body += eq("C1-E29", r"\begin{aligned}\boldsymbol u&=\nabla\phi,\qquad \nabla^2\phi=0,\qquad\frac{d\boldsymbol X}{dt}=\boldsymbol u(\boldsymbol X,t),\\\frac{\partial\phi}{\partial t}&=\frac{p_\infty-p_b-\sigma\kappa}{\rho}-\frac12|\boldsymbol u|^2,\\\frac{D\phi}{Dt}&=\frac{\partial\phi}{\partial t}+\boldsymbol u\cdot\nabla\phi=\frac{p_\infty-p_b-\sigma\kappa}{\rho}+\frac12|\boldsymbol u|^2\qquad(\boldsymbol X\in\Gamma).\end{aligned}",
    r"$\boldsymbol u$ is liquid velocity (m s⁻¹); $\phi$ is velocity potential (m² s⁻¹); $\nabla$ and $\nabla^2$ are spatial gradient and Laplacian; $\boldsymbol X$ is a material interface position (m); $t$ is time (s); $\Gamma$ is the liquid–gas interface; $p_\infty,p_b$ are far-field and bubble pressures (Pa); $\sigma$ is surface tension (N m⁻¹); $\kappa$ is curvature for the liquid-to-gas normal (m⁻¹); $\rho$ is density (kg m⁻³); $D/Dt$ is the material derivative; $|\boldsymbol u|$ is speed and the dot a vector contraction. The potential gauge is fixed at infinity.",
    r"$\boldsymbol u$ 为液体速度（m s⁻¹）；$\phi$ 为速度势（m² s⁻¹）；$\nabla$ 与 $\nabla^2$ 为空间梯度与拉普拉斯；$\boldsymbol X$ 为物质界面点位置（m）；$t$ 为时间（s）；$\Gamma$ 为液—气界面；$p_\infty,p_b$ 为远场与气泡压力（Pa）；$\sigma$ 为表面张力（N m⁻¹）；$\kappa$ 为液体指向气体法向下的曲率（m⁻¹）；$\rho$ 为密度（kg m⁻³）；$D/Dt$ 为物质导数；$|\boldsymbol u|$ 为速率，圆点为矢量缩并。速度势参考值固定在无穷远。",
    "Inviscid pre-impact moving-interface closure", "jet", ["X(t) ∈ Γ", "u = ∇φ", "φ", "∇²φ = 0", "pb", "p∞", "σ", "κ", "ρ", "∂tφ vs Dφ/Dt"], ["Update shape and potential together", "Self-impact or jet piercing requires additional topology and compressibility treatment"], "The interface shape evolves jointly with potential; changing geometry creates focusing.", "界面形状与速度势共同演化，几何变化产生聚焦。")
body += P("As a consistency check, the spherical interface has potential minus radius times wall speed and curvature minus two divided by radius. Insert those values into the last row of Eq. (C1-E29), differentiate the wall potential, and move the squared-speed term to the left. The original inviscid Rayleigh–Plesset equation is recovered. Once a re-entrant jet pierces the opposite interface, the simply connected pre-impact boundary problem is no longer sufficient: topology and rapid pressure transmission need their own treatment.",
    "一致性检查如下：球形界面速度势为半径乘壁面速度的负值，曲率为负二除以半径。将其代入式（C1-E29）最后一行，对壁面速度势求导，再把速度平方项移至左侧，即可恢复原始无黏 Rayleigh–Plesset 方程。一旦再入射流穿透对侧界面，撞击前的单连通边界问题就不再充分；拓扑变化与快速压力传播需要另行处理。")
body += eq("C1-E30", r"\begin{aligned}\phi_\Gamma&=-R\dot R,\qquad\kappa=-\frac2R,\\-\dot R^2-R\ddot R&=\frac{p_\infty-p_b+2\sigma/R}{\rho}+\frac12\dot R^2,\\\rho\left(R\ddot R+\frac32\dot R^2\right)&=p_b-p_\infty-\frac{2\sigma}{R}.\end{aligned}",
    r"$\phi_\Gamma$ is the velocity potential evaluated on the spherical interface (m² s⁻¹), with subscript $\Gamma$ the interface label; $R>0$ is radius (m); $\dot R,\ddot R$ are speed (m s⁻¹) and acceleration (m s⁻²); $\kappa$ is signed liquid-to-gas curvature (m⁻¹); $p_\infty,p_b$ are pressures (Pa); $\sigma$ is surface tension (N m⁻¹); $\rho$ is carrier density (kg m⁻³). The potential is differentiated along the wall; viscosity is zero in this check.",
    r"$\phi_\Gamma$ 为球形界面处速度势（m² s⁻¹），下标 $\Gamma$ 标识界面；$R>0$ 为半径（m）；$\dot R,\ddot R$ 为速度（m s⁻¹）与加速度（m s⁻²）；$\kappa$ 为液体指向气体约定下的带符号曲率（m⁻¹）；$p_\infty,p_b$ 为压力（Pa）；$\sigma$ 为表面张力（N m⁻¹）；$\rho$ 为载液密度（kg m⁻³）。速度势沿壁面求导；此检验中黏度为零。",
    "Exact spherical recovery of the potential closure", "sphere", ["φΓ = −R Ṙ", "κ = −2/R", "R", "Ṙ", "R̈", "pb", "p∞", "σ", "ρ"], ["Recover the same 3/2 coefficient from the material derivative"], "The spatial potential formulation returns the spherical model under spherical geometry.", "空间势流表述在球形几何下恢复球形模型。")
body += eq("C1-E31", r"M_w=\frac{|\dot R|}{c},\qquad \mathcal C_e=\frac{L_e}{c\tau_e}",
    r"$M_w$ is wall Mach number and $\mathcal C_e$ a pressure-communication ratio (both dimensionless); $\dot R$ is wall speed (m s⁻¹); $c>0$ is carrier sound speed (m s⁻¹); $L_e>0$ is the distance across which loading must communicate (m); $\tau_e>0$ is the event's relevant rise or change time (s); $|\ |$ denotes magnitude; subscript $e$ labels the selected event scale.",
    r"$M_w$ 为壁面马赫数，$\mathcal C_e$ 为压力通信比（两者均无量纲）；$\dot R$ 为壁面速度（m s⁻¹）；$c>0$ 为载液声速（m s⁻¹）；$L_e>0$ 为载荷必须传播的距离（m）；$\tau_e>0$ 为事件相关的上升或变化时间（s）；$|\ |$ 表示大小；下标 $e$ 标识选定事件尺度。",
    "Compressibility applicability diagnostics", "timescale", ["Mw = |Ṙ|/c", "Ce = Le/(cτe)", "Ṙ", "c", "Le", "τe", "Pressure propagation path"], ["Small wall Mach alone does not ensure fast pressure communication", "An impact rise time can be much shorter than the total collapse time"], "A pressure pulse can require compressibility even while the bulk wall speed is modest.", "即使总体壁面速率不高，压力脉冲仍可能要求考虑可压缩性。")
body += P("Small wall Mach and a small communication ratio support different aspects of an incompressible approximation. Neither specifies the jet's survival, arriving mass, impact footprint or receiver response. Chapter 3 carries the spatial jet into finite-mass, finite-time observables; Chapter 4 carries its load into release mechanics. Compressibility enters this course through rapid transmission and arrest, rather than through a separate harmonic bubble-oscillation syllabus.",
    "小壁面马赫数与小通信比支持不可压缩近似的不同方面。两者都不能确定射流存活、到达质量、撞击面积或受载体响应。第三章将空间射流连接到有限质量、有限时间观测量；第四章再把载荷连接到释放力学。本课程通过快速传播与运动终止引入可压缩性，而不是另设谐波气泡振荡课程。")
body += note(
    "<strong>What this chapter has closed.</strong> The pressure–inertia equation, its mechanical-energy balance, the ideal collapse integral and a short-impulse benchmark are fully derived. The spatial jet problem is posed with consistent interface conditions. A predictive PFC jet still needs the thermodynamic pressure history, actual geometry and evolving spatial solution. These missing inputs are explicit; an ideal singularity supplies none of them.",
    "<strong>本章已经闭合的内容。</strong> 压力—惯性方程、机械能平衡、理想塌缩积分与短冲量基准均已完整推导。空间射流问题具有一致的界面条件。预测 PFC 射流仍需热力学压力历程、实际几何与随时间演化的空间解。这些缺失输入已明确列出；理想奇异性不能提供其中任何一项。")

body += H("1.8 Three oral-defense questions", "1.8 三道口头答辩问题", "defense-questions")
body += P("These three questions adapt the final research defenses to this chapter's mechanical responsibility. A clear explanation in your own words can demonstrate mastery without reproducing every number. The reference answer starts with the original governing formulas so that each physical claim can be checked against its assumptions. The chapter is not mastered merely because the questions have been written or a response has been saved.",
    "这三道问题将最终研究答辩调整为本章负责的力学内容。用自己的话作出清晰解释即可证明掌握，无须复现所有数值。参考答案先引用原始控制公式，使每个物理判断都能对照其假设核查。问题已经写出或回答已经保存，并不等于本章已经掌握。")

answer1 = eq("C1-E32", r"\rho\left(R\ddot R+\frac32\dot R^2\right)=p_b-p_\infty-\frac{2\sigma}{R}-\frac{4\mu\dot R}{R},\qquad p_b=p_{v,\mathrm{PFC}}+p_{v,w}+p_g",
    r"$\rho$ is carrier density (kg m⁻³); $R>0$ is cavity radius (m); $\dot R,\ddot R$ are wall speed (m s⁻¹) and acceleration (m s⁻²); $p_b,p_\infty$ are total bubble and far-field pressures (Pa); $\sigma$ is surface tension (N m⁻¹); $\mu$ is viscosity (Pa s); $p_{v,\mathrm{PFC}},p_{v,w},p_g$ are PFC-vapor, water-vapor and permanent-gas partial pressures (Pa). The equations are the spherical mechanical balance and the pressure-composition closure target.",
    r"$\rho$ 为载液密度（kg m⁻³）；$R>0$ 为空腔半径（m）；$\dot R,\ddot R$ 为壁面速度（m s⁻¹）与加速度（m s⁻²）；$p_b,p_\infty$ 为气泡总压力与远场压力（Pa）；$\sigma$ 为表面张力（N m⁻¹）；$\mu$ 为黏度（Pa s）；$p_{v,\mathrm{PFC}},p_{v,w},p_g$ 为 PFC 蒸气、水蒸气与非凝结气体分压（Pa）。两式分别为球形力学平衡与需要闭合的压力组成。",
    "Original formulas quoted for defense 1", "phase", ["PFC liquid → vapor", "pv,PFC", "pv,w", "pg", "pb", "p∞", "ρ carrier", "R", "Ṙ", "R̈", "σ", "μ"], ["The pressure history must connect to a specific liquid path"], "The source pressure moves carrier liquid; geometry determines whether that motion is a useful jet.", "源压力使载液运动；几何决定这种运动能否成为有用射流。")
answer1 += P("First I would identify the liquid inventory, absorber location, cavity and force path. Absorption and phase change must provide a pressure history; a low boiling point does not provide that history by itself. The spherical balance then tells me how pressure accelerates mainly the surrounding carrier. Capillarity penalizes expansion and assists inward collapse; viscosity dissipates motion in either direction. The PFC inclusion and the cavity remain separate objects.",
    "我会首先辨认液体库存、吸收体位置、空腔与传力路径。吸收和相变必须提供压力历程；低沸点本身不能给出该历程。球形平衡随后说明压力主要如何加速周围载液。毛细作用阻碍膨胀并促进向内塌缩；黏性在两种运动方向均耗散能量。PFC 夹杂液滴与空腔仍是不同对象。")
answer1 += P("For an external transfer jet I need a liquid outlet, meniscus or other directing geometry, coherent moving liquid and a receiving surface in its path. A collapse jet inside a bubble, a sealed membrane inflation and a pulled liquid bridge have different interfaces and event sequences. A detached film alone cannot identify which occurred. I would track bubble shape, emitted liquid and film motion together. Thermal closure belongs to Chapter 2; fracture and intact placement require Chapters 3 and 4.",
    "外部转印射流需要液体出口、弯月面或其他定向几何，需要相干运动液体，以及位于路径上的受载表面。气泡内部塌缩射流、密闭膜膨胀与被拉出的液桥具有不同界面和事件顺序。仅看到膜脱离不能确定发生了哪种机制。我会同时追踪气泡形状、喷出液体与膜运动。热闭合属于第二章；断裂与完整落位需要第三、四章。")
body += defense("C1-Q1", "Defense 1 — What must happen mechanically between a laser-created cavity and a useful transfer jet?", "答辩 1——从激光产生的空腔到有用的转印射流，力学上必须发生什么？", answer1,
    [("Distinguishes PFC liquid inventory, cavity contents and accelerated carrier, and states that the pressure history needs thermal/phase closure.", "区分 PFC 液体库存、空腔内容物与被加速载液，并说明压力历程需要热与相变闭合。"),
     ("Explains why a radial balance cannot select a jet direction; identifies a concrete asymmetric boundary or outlet.", "解释径向平衡为何不能选定射流方向，并指出具体非对称边界或出口。"),
     ("Distinguishes external ejection, re-entrant penetration, sealed inflation and liquid bridging using observable event order.", "利用可观测事件顺序区分外部喷射、再入穿透、密闭膨胀与液桥。"),
     ("Does not infer successful fracture or intact placement from cavity size or visible release alone.", "不单凭空腔尺寸或可见释放推断成功断裂或完整落位。")])

answer2 = eq("C1-E33", r"\dot R=-\sqrt{\frac{2\Delta p_c}{3\rho}\left[\left(\frac{R_{\max}}R\right)^3-1\right]},\qquad t_c=\frac{B(5/6,1/2)}{\sqrt6}R_{\max}\sqrt{\frac\rho{\Delta p_c}},\qquad K_l=\frac{4\pi}{3}\Delta p_c(R_{\max}^3-R^3)",
    r"$\dot R\le0$ is inward wall velocity (m s⁻¹); $R\in(0,R_{\max}]$ and $R_{\max}$ are current and maximum radii (m); $\Delta p_c>0$ is constant collapse pressure (Pa); $\rho$ is carrier density (kg m⁻³); $t_c$ is ideal collapse time (s); $B$ is the dimensionless beta function defined in Eq. (C1-E17); $K_l$ is carrier kinetic energy (J); $\pi$ is the circle constant. The initial cavity is at rest, with no gas, viscosity, capillarity or compressibility.",
    r"$\dot R\le0$ 为向内壁面速度（m s⁻¹）；$R\in(0,R_{\max}]$ 与 $R_{\max}$ 为当前与最大半径（m）；$\Delta p_c>0$ 为常数塌缩压差（Pa）；$\rho$ 为载液密度（kg m⁻³）；$t_c$ 为理想塌缩时间（s）；$B$ 为式（C1-E17）定义的无量纲贝塔函数；$K_l$ 为载液动能（J）；$\pi$ 为圆周率。初始空腔静止，并忽略非凝结气体、黏性、毛细及可压缩性。",
    "Original formulas quoted for defense 2", "sphere", ["Rmax", "R → 0", "Ṙ < 0", "Δpc", "ρ", "tc", "B(5/6,1/2)/√6", "Kl finite"], ["Finite time and finite energy coexist with an excluded wall-speed singularity"], "The singular velocity belongs to an ideal radial trajectory, not a validated physical maximum.", "奇异速度属于理想径向轨迹，而非经过验证的实际最大值。")
answer2 += P("The coefficient is the integral of a universal dimensionless trajectory, not an empirical material factor. Squared speed reduces the radial equation to a first-order equation with integrating factor radius cubed. The initial zero speed fixes its constant; the negative root fixes collapse. Integrating reciprocal speed and substituting normalized radius cubed yields the beta function and 0.9146813565. Under the same assumptions, four times the pressure halves collapse time; the dimensionless coefficient stays fixed.",
    "该系数是通用无量纲轨迹的积分，并非经验材料因子。速度平方把径向方程约化为一阶方程，其积分因子为半径三次方。初始零速度确定积分常数，负平方根确定塌缩。积分速度倒数，并以无量纲半径三次方换元，可得到贝塔函数与 0.9146813565。在相同假设下，压差变成四倍会使塌缩时间减半；无量纲系数保持不变。")
answer2 += P("The 30 μm control gives 2.744 μs, 11.31 nJ and inward wall speed 21.60 m s⁻¹ at half radius. These are pressure–inertia scales. They do not identify a PFC activation state or outgoing jet. Finite pressure work is consistent with diverging wall speed because the effective radial moving mass decreases with radius cubed. Before zero radius, permanent gas, changing vapor pressure, compressibility, heat/mass transfer or interface distortion can invalidate the model. A point singularity cannot answer a finite-mass maximum-velocity or finite-area, finite-time pressure question.",
    "30 μm 对照给出 2.744 μs、11.31 nJ，以及一半半径处 21.60 m s⁻¹ 的向内壁面速率。这些是压力—惯性尺度，不能辨认 PFC 激活状态或向外射流。有限压力功与壁面速度发散并不矛盾，因为有效径向运动质量按半径三次方减小。到达零半径之前，非凝结气体、变化蒸气压、可压缩性、传热传质或界面变形都可能使模型失效。点奇异性无法回答有限质量的最大速度，或有限面积、有限时间的压力问题。")
body += defense("C1-Q2", "Defense 2 — Why does the Rayleigh coefficient stay fixed when pressure changes, and why is its singular speed not the highest achievable jet speed?", "答辩 2——压差变化时瑞利系数为何不变，其奇异速度为何不是最高可实现射流速度？", answer2,
    [("Connects the coefficient to the nondimensional radius integral, including the initial condition and collapse branch.", "把系数联系到无量纲半径积分，并说明初始条件与塌缩分支。"),
     ("Explains the pressure and radius scaling and gives a consistent numerical or proportionality example.", "解释压差与半径的尺度关系，并给出一致的数值或比例例子。"),
     ("Reconciles finite pressure work with the shrinking inertia scale, then identifies concrete neglected arrest mechanisms.", "用不断缩小的惯性尺度解释有限压力功，再指出具体被忽略的终止机制。"),
     ("Distinguishes radial wall velocity from a directional jet and refuses a universal maximum without defined geometry, mass and observation scale.", "区分径向壁面速度与定向射流，且在几何、质量和观测尺度未定义时不声称通用最大值。")])

answer3 = eq("C1-E34", r"\Pi(\boldsymbol x)=\int_{t_0}^{t_1}(p-p_{\mathrm{ref}})dt,\qquad\Delta\boldsymbol u\simeq-\frac{\nabla\Pi}{\rho},\quad\nabla^2\Pi=0,\qquad U_{\mathrm{column}}=\frac{\Pi_0}{\rho L},\quad t_a=\frac Lc",
    r"$\Pi$ is local pressure impulse (Pa s); $\boldsymbol x$ is fixed position (m); $t,t_0,t_1$ are time and interval endpoints (s); $p,p_{\mathrm{ref}}$ are local and spatially uniform reference pressures (Pa); $\Delta\boldsymbol u$ is liquid speed change (m s⁻¹); $\nabla,\nabla^2$ denote spatial gradient and Laplacian; $\rho$ is carrier density (kg m⁻³); $U_{\mathrm{column}}$ is the ideal straight-column speed increment (m s⁻¹); $\Pi_0$ is driven-end impulse (Pa s); $L$ is column length (m); $t_a$ is crossing time (s); $c$ is sound speed (m s⁻¹). The reduced momentum formula needs a frozen geometry and small omitted impulses.",
    r"$\Pi$ 为局部压力冲量（Pa s）；$\boldsymbol x$ 为固定位置（m）；$t,t_0,t_1$ 为时间与区间端点（s）；$p,p_{\mathrm{ref}}$ 为局部压力与空间均匀参考压力（Pa）；$\Delta\boldsymbol u$ 为液体速度变化（m s⁻¹）；$\nabla,\nabla^2$ 为空间梯度与拉普拉斯；$\rho$ 为载液密度（kg m⁻³）；$U_{\mathrm{column}}$ 为理想直液柱速度增量（m s⁻¹）；$\Pi_0$ 为受驱动端冲量（Pa s）；$L$ 为液柱长度（m）；$t_a$ 为传播时间（s）；$c$ 为声速（m s⁻¹）。约化动量公式要求冻结几何，且被忽略的冲量项较小。",
    "Original formulas quoted for defense 3", "impulse", ["Π(x)", "p − pref", "t₀ → t₁", "Δu ≈ −∇Π/ρ", "ρ", "Π₀", "L", "Ucolumn", "ta = L/c", "c"], ["Pa s is impulse per area; seconds is travel time", "A spatial gradient, not a scalar peak, sets velocity"], "The impulse benchmark gives an early velocity field, followed by a moving-interface problem.", "冲量基准给出早期速度场，之后还需解运动界面问题。")
answer3 += P("I would first define the driven boundary, outlet, initial meniscus and receiver geometry. The pressure pulse must be integrated at each location. Two pulses with the same peak can have different duration and impulse; two domains with the same scalar impulse can have different spatial gradients. The gradient determines early liquid velocity, while the boundary-value problem determines that gradient. A uniform addition to impulse cannot accelerate the liquid.",
    "我会先定义受驱动边界、出口、初始弯月面及受载几何。需要在每个位置对压力脉冲积分。两个峰值相同的脉冲可具有不同持续时间与冲量；两个标量冲量相同的区域也可具有不同空间梯度。梯度决定早期液体速度，而边值问题决定该梯度。空间均匀增加冲量不能加速液体。")
answer3 += P("The teaching column gives 0.30 Pa s and 3.0 m s⁻¹ under its endpoint conditions. Its 0.0667 μs crossing time is a separate quantity. Several crossings make communication plausible on the pulse timescale but do not establish uniformity or exactness. I would check displacement, convection and viscosity, then evolve the actual interface with stress, pressure and contact-line conditions. Only that spatial evolution determines focusing and an outgoing jet. The thermodynamic pressure history remains necessary, and a rapidly changing or impacting state may require compressibility even when a nominal bulk speed is low.",
    "教学液柱在其端点条件下给出 0.30 Pa s 与 3.0 m s⁻¹。其 0.0667 μs 传播时间是另一物理量。多次传播使脉冲时间内的通信具有可能性，却不能证明空间均匀或解的精确性。我会检验位移、对流与黏性，再用应力、压力及接触线条件演化实际界面。只有该空间演化才能决定聚焦与向外射流。热力学压力历程仍然必需；即使名义总体速率较低，快速变化或撞击状态也可能需要考虑可压缩性。")
body += defense("C1-Q3", "Defense 3 — Why are neither a pressure peak nor a short sound-crossing time enough to predict a transfer jet?", "答辩 3——为什么压力峰值与短声传播时间都不足以预测转印射流？", answer3,
    [("Distinguishes pressure (Pa), pressure impulse (Pa s), momentum (N s) and crossing time (s), without equating their units.", "区分压力（Pa）、压力冲量（Pa s）、动量（N s）与传播时间（s），不混淆其单位。"),
     ("Uses the spatial impulse gradient and actual boundary conditions to explain the initial velocity; a scalar peak is insufficient.", "利用空间冲量梯度与实际边界条件解释初始速度，说明单一峰值不足。"),
     ("Explains what the ideal column predicts and what its small-displacement and residual-impulse diagnostics do not guarantee.", "解释理想液柱预测的内容，以及小位移与残余冲量诊断不能保证的内容。"),
     ("Identifies the subsequent moving-interface, pressure, phase-transfer and compressibility information needed for a physical jet.", "指出实际射流还需要后续运动界面、压力、相变传质与可压缩性信息。")])

CHAPTER = {
    "number": 1,
    "slug": "01-cavity-pressure-inertia-and-directional-jets",
    "title_en": "Cavity pressure, carrier inertia and directional jets",
    "title_zh": "空腔压力、载液惯性与定向射流",
    "summary_en": "Derive radial dynamics and energy, solve the Rayleigh integral, and close the spatial problem that turns liquid motion into a jet.",
    "summary_zh": "推导径向动力学与能量，解出瑞利积分，并闭合把液体运动变为射流的空间问题。",
    "body": body,
    "question_ids": ["C1-Q1", "C1-Q2", "C1-Q3"],
    "objectives": [
        ("Classify the cavity and liquid force path before using a jet model.", "使用射流模型之前，辨认空腔与液体传力路径。"),
        ("Reconstruct Rayleigh–Plesset with the correct fixed-position potential derivative.", "使用正确的固定位置速度势导数，重建 Rayleigh–Plesset 方程。"),
        ("Derive pressure-work conservation and the beta-function collapse coefficient.", "推导压力功守恒与贝塔函数塌缩系数。"),
        ("Explain why impulse, boundaries and evolving interface shape are needed for a directional jet.", "解释定向射流为何需要冲量、边界与演化界面形状。"),
    ],
    "prerequisite_en": "Introductory mechanics and calculus; no prior cavitation training. Pressure input is declared here and derived thermodynamically in Chapter 2.",
    "prerequisite_zh": "基础力学与微积分；不要求空化背景。本章声明压力输入，第二章从热力学推导该输入。",
}
