"""Explicit bilingual glossary rows: one symbol, one definition, one role."""

def v(symbol,en,zh,unit,role_en,role_zh):
    return (symbol,en,zh,unit,role_en,role_zh)

GLOSSARIES={
1:[
v(r't','Elapsed time','经过时间','s','Independent time coordinate; the initial instant is t = 0.','独立时间坐标；初始时刻取 t = 0。'),
v(r'r','Liquid radial coordinate','液体径向坐标','m','Distance from the fixed cavity center to an observation point in the carrier; r ≥ R.','从固定空腔中心到载液中观察点的距离；r ≥ R。'),
v(r'R','Instantaneous cavity radius','瞬时空腔半径','m','Locates the moving liquid–bubble interface; it is not the initial PFC-core radius.','定位运动的液体—气泡界面；并非初始 PFC 核半径。'),
v(r'\dot R','Wall radial velocity','壁面径向速度','m s⁻¹','First time derivative of R; positive means expansion and negative means collapse.','R 对时间的一阶导数；正值表示膨胀，负值表示塌缩。'),
v(r'\ddot R','Wall radial acceleration','壁面径向加速度','m s⁻²','Second time derivative of R; its sign describes velocity change, not motion direction alone.','R 对时间的二阶导数；其符号描述速度变化，不能单独代表运动方向。'),
v(r'R_0','Prescribed initial cavity radius','给定初始空腔半径','m','Positive initial value R(0); a state input to the mechanical model.','正的初始值 R(0)；是力学模型的状态输入。'),
v(r'U_0','Initial wall velocity','初始壁面速度','m s⁻¹','Prescribed value of the first time derivative of R at the initial instant.','初始时刻给定的 R 的一阶时间导数。'),
v(r'\rho','Carrier mass density','载液质量密度','kg m⁻³','Sets surrounding-liquid inertia; it must not be replaced by PFC vapor density.','决定周围液体的惯性；不能替换成 PFC 蒸气密度。'),
v(r'\mu','Carrier dynamic viscosity','载液动力黏度','Pa s','Newtonian stress coefficient; viscous resistance dissipates energy in either motion direction.','牛顿流体应力系数；黏性阻力在两个运动方向均耗散能量。'),
v(r'\sigma','Effective bubble–carrier surface tension','有效气泡—载液表面张力','N m⁻¹','Belongs to the specified interface; contributes the spherical capillary pressure 2σ/R.','属于指定界面；产生球形毛细压力 2σ/R。'),
v(r'p_b','Uniform bubble absolute pressure','均匀气泡绝对压力','Pa','Pressure on the cavity side of the interface; its history is supplied here.','界面空腔侧压力；本章将其时间历程作为输入。'),
v(r'p_l','Adjacent-liquid absolute pressure','邻近液体绝对压力','Pa','Liquid-side pressure at the moving interface; stress balance relates it to bubble pressure.','运动界面的液体侧压力；通过应力平衡与泡内压力关联。'),
v(r'p_\infty','Far-field absolute pressure','远场绝对压力','Pa','Pressure prescribed far from the cavity; pressure differences drive acceleration.','远离空腔处的给定压力；加速度由压力差驱动。'),
v(r'p','Liquid pressure field','液体压力场','Pa','Pressure at a general liquid observation point, evaluated at the stated position and time.','指定位置与时间的普通液体观察点压力。'),
v(r'u','Scalar radial carrier velocity','标量载液径向速度','m s⁻¹','Positive outward from the center; differs from the spatial velocity vector below.','从中心向外取正；与下文空间速度矢量区别使用。'),
v(r'C(t)','Radial volume-flux factor','径向体积流量因子','m³ s⁻¹','Continuity makes r²u independent of r; this function is not a material constant.','连续性使 r²u 与 r 无关；该函数并非材料常数。'),
v(r'\phi','Velocity potential','速度势','m² s⁻¹','Its spatial derivative gives radial velocity; the reference value is fixed at infinity.','其空间导数给出径向速度；参考值固定在无穷远。'),
v(r'V_b','Cavity volume','空腔体积','m³','Geometric volume enclosed by the bubble boundary; pressure work uses its rate of change.','气泡边界围成的几何体积；压力功使用其变化率。'),
v(r'K_l','Carrier kinetic energy','载液动能','J','Integrates motion throughout the exterior liquid, rather than mass inside the bubble.','对外部液体的运动进行积分，而不是计算气泡内部质量。'),
v(r'E_\sigma','Interfacial energy','界面能','J','Surface tension multiplied by spherical interface area under the constant-tension assumption.','在张力恒定假设下，等于表面张力乘球形界面面积。'),
v(r'R_{\max}','Radius at the start of ideal collapse','理想塌缩开始时的半径','m','Maximum cavity radius with zero initial wall velocity in the Rayleigh control.','Rayleigh 对照中壁面初始速度为零时的最大空腔半径。'),
v(r'p_v','Stipulated constant vapor pressure','假定恒定蒸气压','Pa','Ideal-collapse internal-pressure input; real thermal or finite-inventory evolution may change it.','理想塌缩的内部压力输入；实际热过程或有限存量变化可能改变它。'),
v(r'\Delta p_c','Positive ideal-collapse pressure difference','正的理想塌缩压差','Pa','Defined as far-field pressure minus the stipulated vapor pressure in this control.','在该对照中定义为远场压力减去假定蒸气压。'),
v(r't_c','Ideal collapse time','理想塌缩时间','s','Time from the initial maximum radius to the excluded zero-radius limit of the ideal model.','从初始最大半径到理想模型所排除的零半径极限的时间。'),
v(r'E_B','Displaced-volume pressure-work scale','排开体积的压力功尺度','J','Uses the stated pressure difference and initial cavity volume; not an assigned jet energy.','由所声明压差与初始空腔体积构成；并非预设的射流能量。'),
v(r'\boldsymbol x','Spatial position vector','空间位置矢量','m','Locates a point in the nonspherical liquid domain.','定位非球形液体域中的一点。'),
v(r'\boldsymbol u','Spatial carrier velocity vector','空间载液速度矢量','m s⁻¹','Contains direction and spatial variation needed for a jet; scalar wall speed is insufficient.','包含射流所需的方向与空间变化；标量壁面速度不足以替代它。'),
v(r'\Pi','Pressure impulse per unit area','单位面积压力冲量','Pa s','Time integral of the specified excess pressure; its gradient changes liquid velocity.','指定超压对时间的积分；其梯度改变液体速度。'),
v(r'\Gamma','Moving liquid–gas interface','运动液—气界面','—','Geometric surface, not fracture energy; its position evolves with the interface condition.','几何曲面，不是断裂能；其位置按界面条件演化。'),
v(r'\boldsymbol n','Liquid-to-gas unit normal','液体指向气体的单位法向','1','Fixes traction and signed-curvature conventions; reversing it changes those signs.','确定牵引与带符号曲率约定；反转法向会改变相关符号。'),
v(r'\kappa','Signed sum of principal curvatures','带符号的两主曲率之和','m⁻¹','For the stated liquid-to-gas normal on a spherical cavity, κ = −2/R.','对于所声明的球形空腔液体指向气体法向，κ = −2/R。'),
],
2:[
v(r'F','Laser fluence','激光能量面密度','J m⁻²','Pulse energy incident per unit area; it is a time integral, not an instantaneous irradiance.','单位面积接收的脉冲能量；是时间积分，而非瞬时辐照度。'),
v(r'I','Laser irradiance','激光辐照度','W m⁻²','Instantaneous optical power per unit area; integrating it over the pulse gives fluence.','单位面积上的瞬时光功率；对脉冲历时积分得到能量面密度。'),
v(r'E_L','Incident laser-pulse energy','入射激光脉冲能量','J','Total incident optical budget before interception, reflection and absorption losses.','截获、反射及吸收损失之前的总入射光能预算。'),
v(r'E_{\mathrm{abs}}','Absorbed optical energy','吸收光能','J','Energy actually deposited in the defined absorber; not necessarily heat delivered to PFC.','实际沉积在指定吸收体中的能量；不一定等于传给 PFC 的热量。'),
v(r'T','Thermodynamic temperature','热力学温度','K','Local state in the heat/phase balance; phase equilibrium and rate laws require its history.','热／相平衡中的局部状态；相平衡与速率规律需要其时间历程。'),
v(r'\rho','Local material mass density','局部材料质量密度','kg m⁻³','The material or phase must be specified; PFC heating density and carrier inertia density differ.','必须指定材料或相；PFC 加热密度与载液惯性密度不同。'),
v(r'c_p','Specific heat capacity at constant pressure','定压比热容','J kg⁻¹ K⁻¹','Sensible-heat capacity per mass; constant-property examples are declared approximations.','单位质量的显热容量；恒物性例题是明确声明的近似。'),
v(r'k','Thermal conductivity','导热系数','W m⁻¹ K⁻¹','Relates temperature gradient to conductive heat flux, not to fluid permeability.','关联温度梯度与导热热流，不是流体渗透率。'),
v(r'\alpha','Thermal diffusivity','热扩散率','m² s⁻¹','Conductivity divided by volumetric heat capacity; determines thermal communication time.','导热系数除以体积热容量；决定热传播时间。'),
v(r'a_0','Initial liquid-PFC core radius','初始液态 PFC 核半径','m','Defines the initial finite liquid inventory; not the growing vapor-cavity radius.','确定初始有限液体存量；并非增长中的蒸气腔体半径。'),
v(r'R','Subsequent bubble radius','后续气泡半径','m','Geometric cavity coordinate after activation; by itself it does not determine phase mass.','激活后的几何空腔坐标；仅凭它无法确定各相质量。'),
v(r'V_b','Bubble volume','气泡体积','m³','Volume enclosing the vapor/gas mixture; requires mass, temperature and pressure closure.','蒸气／气体混合物所在体积；需要质量、温度与压力闭合。'),
v(r'm_l','Remaining liquid-PFC mass','剩余液态 PFC 质量','kg','Liquid reservoir remaining after signed interfacial phase transfer.','带符号界面相变传递之后剩余的液体储量。'),
v(r'm_v','PFC vapor mass','PFC 蒸气质量','kg','Vapor inventory, constrained by the original core and any stated transport sources.','蒸气存量，受原始液核及所声明传输源约束。'),
v(r'j_s','Signed species phase-transfer mass flux','带符号组分相变质量通量','kg m⁻² s⁻¹','Mass crossing unit interfacial area per time; the chosen evaporation direction fixes its sign.','单位界面面积每单位时间穿过的质量；所选蒸发方向确定其符号。'),
v(r'\sigma_{pc}','PFC–carrier interfacial tension','PFC—载液界面张力','N m⁻¹','Acts at the original liquid-droplet boundary; not the vapor–PFC nucleation tension.','作用于原始液滴边界；不是蒸气—PFC 成核张力。'),
v(r'\sigma_{vp}','Vapor–liquid-PFC interfacial tension','蒸气—液态 PFC 界面张力','N m⁻¹','Belongs to the vapor nucleus inside PFC and its capillary/nucleation cost.','属于 PFC 内部蒸气核及其毛细／成核代价。'),
v(r'U_b','Bubble internal energy','气泡内能','J','Thermodynamic energy of the cavity contents; changes by heat, phase enthalpy and boundary work.','腔内物质的热力学能量；由热、相变焓与边界功改变。'),
v(r'h_s','Transported species specific enthalpy','输运组分比焓','J kg⁻¹','Enthalpy carried with unit transferred species mass; phase and state must be specified.','单位传递组分质量携带的焓；必须指定相与状态。'),
v(r'M_s','Species molar mass','组分摩尔质量','kg mol⁻¹','Converts species mass to amount of substance in the chosen equation of state.','在所选状态方程中，将组分质量换算为物质的量。'),
v(r'L_{v,s}','Species-specific latent heat of vaporization','组分汽化比潜热','J kg⁻¹','Phase-change energy per converted species mass; the interface state and approximation are specified.','单位转化组分质量的相变能量；需指定界面状态与近似。'),
v(r'R_u','Universal molar gas constant','通用摩尔气体常数','J mol⁻¹ K⁻¹','Used with amount of substance, not silently with mass-specific variables.','与物质的量共同使用，不能默默代入质量比形式。'),
],
3:[
v(r'i','Index of the bubble being evaluated','当前评估气泡的编号','1','Integer from 1 to the activated-bubble count; selects the local radial equation.','从 1 到已激活气泡数的整数；选择局部径向方程。'),
v(r'j','Index of a neighboring bubble','相邻气泡的编号','1','In an interaction sum the evaluated site is excluded: j ≠ i.','相互作用求和中排除当前位点：j ≠ i。'),
v(r'N_d','Fabricated droplet-site count','制造的液滴位点数','1','Counts available sites; it does not imply every site activates.','计数可用位点；不意味着每个位点都激活。'),
v(r'N_b','Activated-bubble count','已激活气泡数','1','Counts actual bubble sources used in the interaction equations.','计数相互作用方程中实际使用的气泡源。'),
v(r'R_i','Radius of bubble i','气泡 i 的半径','m','Moving radial coordinate of the selected bubble; Newton dots denote its time derivatives.','选定气泡的运动径向坐标；牛顿点号表示其时间导数。'),
v(r'd_{ij}','Bubble-center separation','气泡中心间距','m','Distance between centers i and j; reciprocal distance weights dilute interactions.','中心 i 与 j 的距离；距离倒数加权稀疏相互作用。'),
v(r's','Nearest-vertex array pitch','阵列相邻顶点间距','m','Defined nearest-neighbor spacing in the regular-polygon control.','正多边形对照中定义的最近邻间距。'),
v(r'R_{\max}','Maximum bubble radius','最大气泡半径','m','Reference radius for the specified collapse control and geometric interaction parameter.','指定塌缩对照与几何相互作用参数采用的参考半径。'),
v(r'\rho','Carrier-liquid density','载液密度','kg m⁻³','Sets bubble-exterior inertia and emitted liquid mass; not PFC-vapor density.','决定泡外惯性与喷出液体质量；不是 PFC 蒸气密度。'),
v(r'\mu','Carrier dynamic viscosity','载液动力黏度','Pa s','Controls viscous stresses and jet dissipation in the stated liquid model.','在指定液体模型中控制黏性应力及射流耗散。'),
v(r'\sigma_b','Bubble-interface surface tension','气泡界面表面张力','N m⁻¹','Bubble capillary coefficient; need not equal the jet-interface coefficient.','气泡毛细系数；不必等于射流界面系数。'),
v(r'\sigma_j','Jet-interface surface tension','射流界面表面张力','N m⁻¹','Coefficient for the emitted jet and its capillary disturbance growth.','喷出射流及其毛细扰动增长使用的系数。'),
v(r'c','Liquid sound speed','液体声速','m s⁻¹','Sets acoustic transit and ideal early-contact impedance, not a universal jet-speed ceiling.','决定声传播时间及理想早期接触阻抗，并非通用射流速度上限。'),
v(r'\phi','Velocity potential','速度势','m² s⁻¹','Its spatial gradient gives the adopted potential-flow velocity.','其空间梯度给出所采用的势流速度。'),
v(r'\Pi','Pressure impulse per unit area','单位面积压力冲量','Pa s','Pressure integrated over a stated time interval; distinct from total force impulse.','指定时间区间内的压力积分；与总力冲量不同。'),
v(r'\boldsymbol u','Liquid velocity field','液体速度场','m s⁻¹','Vector field needed to distinguish focusing, jet formation and transport.','用于区分聚焦、射流形成与输运的矢量场。'),
v(r'E','Specified mechanical energy','指定力学能量','J','The subscript identifies its budget; optical, bubble and jet energies are not interchangeable.','下标标识预算对象；光能、气泡能与射流能不能混同。'),
v(r'm','Finite moving-liquid mass','有限运动液体质量','kg','Mass of the declared jet or control volume used in energy and momentum bounds.','能量与动量界限中所声明射流或控制体的质量。'),
v(r'P','Directional liquid momentum','液体方向动量','N s','Projection of moving-liquid momentum along the selected transfer direction.','运动液体动量沿选定转印方向的投影。'),
v(r'\mathcal J','Delivered force impulse','传递的力冲量','N s','Time integral of force at the specified target; not pressure impulse per area.','指定目标处的力对时间的积分；不是单位面积压力冲量。'),
v(r'a_j','Jet radius','射流半径','m','Half the declared circular jet diameter; sets lateral-release and capillary scales.','所声明圆形射流直径的一半；决定侧向释放与毛细尺度。'),
v(r'd_j','Jet diameter','射流直径','m','Transverse size used with emitted length to determine finite jet volume.','与喷出长度共同确定有限射流体积的横向尺寸。'),
v(r'L_j','Finite emitted-jet length','有限喷出射流长度','m','Longitudinal liquid inventory; must not be replaced by an unlimited steady stream.','液体纵向存量；不能替换为无限稳态液流。'),
v(r'H','Flight gap','飞行间隙','m','Distance traveled by the emitted liquid before reaching the specified target.','喷出液体到达指定目标之前经过的距离。'),
v(r'z','Jet axial coordinate','射流轴向坐标','m','Coordinate along the transport direction used for slice conservation.','用于切片守恒的输运方向坐标。'),
v(r'S','Neighbor reciprocal-distance sum','邻距倒数和','m⁻¹','Finite sum of the inverse center separations in the regular-array control.','规则阵列对照中中心间距倒数的有限和。'),
v(r'\chi','Dimensionless interaction parameter','无量纲相互作用参数','1','Maximum radius multiplied by S; quantifies interaction within the adopted dilute model.','最大半径乘以 S；量化所采用稀疏模型中的相互作用。'),
v(r'C(\chi)','Formal collapse-time coefficient','形式塌缩时间系数','1','Result of the stated array-control integral; not a pressure amplification factor.','指定阵列对照积分的结果；不是压力放大系数。'),
v(r'b_i','Radial source strength of bubble i','气泡 i 的径向源强度','m³ s⁻¹','Defined by radius squared times wall velocity in the monopole-flow control.','在单极流动对照中定义为半径平方乘壁面速度。'),
v(r'\Gamma','Moving liquid interface','运动液体界面','—','Geometric surface carrying kinematic and traction conditions; not fracture energy.','承载运动学及牵引条件的几何曲面；不是断裂能。'),
v(r'\Omega','Liquid spatial domain','液体空间域','—','Region occupied by liquid in the spatial-flow problem.','空间流动问题中液体占据的区域。'),
v(r'\boldsymbol n','Outward liquid unit normal','液体外向单位法向','1','Points out of liquid; fixes traction and signed curvature.','指向液体外部；确定牵引及带符号曲率。'),
v(r'\kappa','Signed interfacial curvature','带符号界面曲率','m⁻¹','Sum of principal curvatures for the stated normal convention.','在指定法向约定下的两主曲率之和。'),
v(r'g','Disturbance growth rate','扰动增长率','s⁻¹','Exponential capillary growth coefficient; this symbol is not gravitational acceleration.','指数毛细增长系数；该符号不是重力加速度。'),
v(r'\delta','Jet-radius disturbance amplitude','射流半径扰动振幅','m','Small deviation from the undeformed jet; linear growth ceases to apply at large amplitude.','相对未变形射流的小偏差；大振幅时线性增长不再适用。'),
v(r'k','Axial disturbance wavenumber','轴向扰动波数','m⁻¹','Spatial oscillation frequency along the jet; not thermal conductivity.','沿射流的空间振荡频率；不是导热系数。'),
v(r'q','Dimensionless disturbance wavenumber','无量纲扰动波数','1','Defined as axial wavenumber multiplied by jet radius.','定义为轴向波数乘射流半径。'),
v(r'I_0','Modified Bessel function of order zero','零阶修正 Bessel 函数','1','Dimensionless radial eigenfunction in the cylindrical capillary control.','圆柱毛细对照中的无量纲径向特征函数。'),
v(r'I_1','Modified Bessel function of order one','一阶修正 Bessel 函数','1','Used with I₀ in the stated disturbance dispersion relation.','在指定扰动色散关系中与 I₀ 共同使用。'),
v(r'Z_l','Liquid acoustic impedance','液体声阻抗','Pa s m⁻¹','Density times sound speed in the adopted one-dimensional early-contact model.','在所采用的一维早期接触模型中为密度乘声速。'),
v(r'Z_r','Receiver acoustic impedance','接收体声阻抗','Pa s m⁻¹','Determines early wave matching; finite thickness and motion can invalidate the half-space control.','决定早期波匹配；有限厚度与运动可能使半空间对照失效。'),
v(r'A_o','Pressure observation area','压力观测面积','m²','Fixed footprint over which the reported load is spatially averaged.','用于对报告载荷进行空间平均的固定范围。'),
v(r'\tau_o','Pressure averaging interval','压力平均时间区间','s','Specified time window; changing it changes the observable pressure.','指定时间窗口；改变它会改变可观测压力。'),
v(r'p_{\mathrm{obs}}','Observed mean excess pressure','观测平均超压','Pa','Area/time average on the defined target; differs from a brief local pressure spike.','指定目标上的面积／时间平均；不同于短暂局部压力尖峰。'),
],
4:[
v(r'\boldsymbol n_f','Solid-to-liquid unit normal','固体指向液体的单位法向','1','At a film with liquid below, it points downward; pressure traction can still push upward.','对于下方接触液体的薄膜，该法向向下；压力牵引仍可向上推动。'),
v(r'\boldsymbol t_l','Liquid traction on the solid','液体施加于固体的牵引','Pa','Stress contracted with the specified normal at the exposed face.','外露面上应力与指定法向的收缩。'),
v(r'p','Liquid absolute pressure','液体绝对压力','Pa','Acts compressively on the exposed face; release-interface opening depends on structural motion.','对外露面产生压缩作用；释放界面张开取决于结构运动。'),
v(r'q','Signed transverse applied load','带符号横向外加载荷','Pa','Positive in the upward film-opening direction; distinguishes applied pressure from net reactions.','沿薄膜向上张开方向取正；区分外加压力与净反力。'),
v(r'w','Film transverse displacement','薄膜横向位移','m','Positive upward; its spatial profile determines bending and interface opening.','向上取正；其空间分布决定弯曲与界面张开。'),
v(r'\dot w','Film transverse velocity','薄膜横向速度','m s⁻¹','First time derivative of displacement; enters kinetic energy and power.','位移的一阶时间导数；进入动能及功率计算。'),
v(r'\ddot w','Film transverse acceleration','薄膜横向加速度','m s⁻²','Second time derivative of displacement; gives the areal inertial load.','位移的二阶时间导数；给出单位面积惯性载荷。'),
v(r'h_f','Film thickness','薄膜厚度','m','Controls areal mass and the cubic thickness dependence of bending rigidity.','控制面质量及弯曲刚度对厚度的三次方依赖。'),
v(r'\rho_f','Film mass density','薄膜质量密度','kg m⁻³','Solid density used in areal mass; distinct from the incoming liquid density.','面质量采用的固体密度；与入射液体密度不同。'),
v(r'E_f','Film Young’s modulus','薄膜杨氏模量','Pa','Elastic stiffness for the declared thin-plate constitutive control.','指定薄板本构对照的弹性刚度参数。'),
v(r'\nu_f','Film Poisson’s ratio','薄膜泊松比','1','Relates transverse and longitudinal elastic strains within the adopted isotropic model.','在所采用各向同性模型中关联横向与纵向弹性应变。'),
v(r'D_f','Film bending rigidity','薄膜弯曲刚度','N m','Combines modulus, thickness and Poisson’s ratio; not a diffusivity or strain-rate tensor.','结合模量、厚度与泊松比；不是扩散率或应变率张量。'),
v(r'\Gamma','Practical interfacial fracture energy','实际界面断裂能','J m⁻²','Resistance per newly released area under the relevant mode and rate; not a geometric surface here.','相关模式与速率下单位新释放面积的阻力；此处不是几何曲面。'),
v(r'G','Mechanical energy-release rate','力学能量释放率','J m⁻²','Energy available per incremental crack area; compared with fracture resistance.','单位增量裂纹面积可获得的能量；与断裂阻力比较。'),
v(r'T_{\max}','Peak tensile cohesive traction','峰值拉伸内聚牵引','Pa','Local cohesive strength; not equivalent to interfacial fracture energy.','局部内聚强度；不等同于界面断裂能。'),
v(r'\delta','Relative opening of the release interface','释放界面相对张开量','m','Relative displacement across the bonded interface; not the absolute displacement of one film.','粘接界面两侧的相对位移；不是某一薄膜的绝对位移。'),
v(r'a','Circular released/blister radius','圆形释放／鼓泡区域半径','m','Defines the crack front and domain size in the clamped circular-plate control.','在固支圆板对照中定义裂纹前缘与区域尺度。'),
v(r't','Time','时间','s','Independent coordinate for pulse loading, inertia and fracture evolution.','脉冲受载、惯性及断裂演化的独立坐标。'),
v(r'\nabla_\parallel','Film-plane spatial gradient','薄膜平面空间梯度','m⁻¹','Differentiates within the plate plane; it is an operator rather than a material parameter.','在薄板平面内求导；是算子，而非材料参数。'),
],
5:[
v(r't','Time','时间','s','Independent coordinate of the transient cavity event; the reference state is specified at zero.','瞬态腔体事件的独立坐标；参考状态规定在零时刻。'),
v(r'r_0','Reference material radial coordinate','参考材料径向坐标','m','Labels a material shell in the stress-free configuration; held fixed for material motion.','标识无应力构形中的材料壳层；追踪材料运动时保持不变。'),
v(r'r','Current material radial coordinate','当前材料径向坐标','m','Current position of the shell labeled by r₀; distinct from current wall radius R.','由 r₀ 标识的壳层当前所在位置；不同于当前壁面半径 R。'),
v(r'R_{\mathrm{ref}}','Stress-free reference cavity radius','无应力参考腔体半径','m','Reference geometry for network stretch; not automatically an observed loaded cavity radius.','网络伸长的参考几何；不能自动等同于观测到的受载腔体半径。'),
v(r'R','Current cavity radius','当前腔体半径','m','Locates the moving cavity boundary in the current configuration.','定位当前构形中的运动腔体边界。'),
v(r'\dot R','Cavity wall radial velocity','腔体壁面径向速度','m s⁻¹','First time derivative of R; positive expansion and negative inward motion.','R 的一阶时间导数；正值表示膨胀，负值表示向内运动。'),
v(r'\ddot R','Cavity wall radial acceleration','腔体壁面径向加速度','m s⁻²','Second time derivative of R in the inertial radial balance.','惯性径向平衡中的 R 的二阶时间导数。'),
v(r'a_0','Initial liquid-PFC core radius','初始液态 PFC 核半径','m','Inventory geometry; neither R nor the network reference radius is silently substituted for it.','存量几何；不能默默用 R 或网络参考半径替代它。'),
v(r'\lambda_r','Radial principal stretch','径向主伸长','1','Ratio of current to reference radial line elements at a material shell.','材料壳层处当前与参考径向线元的比值。'),
v(r'\lambda_\theta','First tangential principal stretch','第一切向主伸长','1','Circumferential line-element ratio in the θ direction.','θ 方向周向线元的比值。'),
v(r'\lambda_\phi','Second tangential principal stretch','第二切向主伸长','1','Circumferential line-element ratio in the φ direction; equals the other tangential stretch under spherical symmetry.','φ 方向周向线元的比值；在球对称下等于另一切向伸长。'),
v(r'\mathbf F','Deformation-gradient tensor','变形梯度张量','1','Maps reference line elements into the current configuration.','将参考线元映射到当前构形。'),
v(r'\mathbf B','Left Cauchy–Green tensor','左 Cauchy—Green 张量','1','Product of deformation gradient and its transpose; enters the neo-Hookean stress.','变形梯度与其转置的乘积；进入 neo-Hookean 应力。'),
v(r'G_g','Gel-network shear modulus','凝胶网络剪切模量','Pa','Elastic material parameter controlling stored network resistance; relevant strain/rate dependence must be validated.','控制所储存网络阻力的弹性材料参数；相关应变／速率依赖需验证。'),
v(r'\eta_g','Represented Kelvin–Voigt viscosity','所描述的 Kelvin—Voigt 黏度','Pa s','Coefficient of the adopted viscous stress; avoid counting the same solvent dissipation twice.','所采用黏性应力的系数；避免对同一溶剂耗散重复计数。'),
v(r'\rho_g','Effective medium mass density','有效介质质量密度','kg m⁻³','Density of the moving surrounding medium, not the PFC core or vapor alone.','周围运动介质的密度，不是单独的 PFC 核或蒸气密度。'),
v(r'\sigma','Cavity-interface tension','腔体界面张力','N m⁻¹','Constant coefficient for the declared interface; separate from network elastic stress.','指定界面的恒定系数；与网络弹性应力不同。'),
v(r'\mathbf T^e','Elastic Cauchy-stress tensor','弹性 Cauchy 应力张量','Pa','Tensile-positive stress contributed by the network constitutive law; e denotes elasticity.','网络本构规律产生的应力，拉伸为正；e 表示弹性。'),
v(r'\mathbf T','Total Cauchy-stress tensor','总 Cauchy 应力张量','Pa','Includes elastic and represented viscous contributions in the radial momentum balance.','包含径向动量平衡中的弹性及所描述黏性贡献。'),
v(r'\chi','Incompressibility multiplier','不可压缩约束乘子','Pa','Unknown isotropic stress multiplier; unlike Chapter 3’s interaction parameter, it has pressure units here.','未知各向同性应力乘子；与第三章的相互作用参数不同，此处具有压力单位。'),
v(r'p_b','Uniform cavity absolute pressure','均匀腔内绝对压力','Pa','Supplied by the laser/phase source calculation, not derived from the elastic resistance.','由激光／相变源计算提供，不由弹性阻力推导。'),
v(r'p_\infty','Far-field absolute pressure','远场绝对压力','Pa','Sets the exterior radial-traction condition under the stated stress convention.','在指定应力约定下确定外部径向牵引条件。'),
v(r'p_{\mathrm{el}}','Signed elastic cavity resistance','带符号弹性腔体阻力','Pa','Stress-difference integral resisting expansion; its intact-network formula is not a fracture threshold.','抵抗膨胀的应力差积分；其完整网络公式不是断裂阈值。'),
v(r'u_r','Radial material velocity','材料径向速度','m s⁻¹','Velocity of the surrounding material, consistent with the stated no-phase-slip control.','周围材料的速度，与所声明无相间滑移对照一致。'),
v(r'\mathbf D','Symmetric velocity-gradient tensor','对称速度梯度张量','s⁻¹','Strain-rate tensor used by the represented viscous constitutive law.','所描述黏性本构规律使用的应变率张量。'),
v(r'W_g','Stored network elastic work','储存的网络弹性功','J','Integrated recoverable network work measured from the stress-free reference cavity.','从无应力参考腔体起算的可恢复网络功积分。'),
v(r'K_g','Surrounding-medium kinetic energy','周围介质动能','J','Integrated energy of the radial exterior motion.','外部径向运动能量的积分。'),
v(r'E_\sigma','Cavity surface energy','腔体表面能','J','Interface-area energy under the declared constant-tension assumption.','指定恒张力假设下的界面面积能量。'),
v(r'P_{\mathrm{dis}}','Nonnegative viscous dissipation power','非负黏性耗散功率','W','Rate of irreversible mechanical-energy loss; differs from recoverable storage.','不可逆力学能损失速率；不同于可恢复储能。'),
v(r'\tau_e','Event duration','事件持续时间','s','Specified loading/evolution time used to test material-response assumptions.','检验材料响应假设采用的指定受载／演化时间。'),
v(r'\tau_{\mathrm{rel}}','Measured stress-relaxation time','测量的应力松弛时间','s','Independently identified memory time; not Kelvin–Voigt retardation time.','独立确定的记忆时间；不是 Kelvin—Voigt 延迟时间。'),
v(r'L_g','Specified gel communication length','指定凝胶传播长度','m','Distance over which shear support or solvent drainage must communicate.','剪切支撑或溶剂排水需要传播的距离。'),
v(r'\mathrm{De}','Deborah number','Deborah 数','1','Stress-relaxation time divided by event duration in the declared memory test.','在指定记忆检验中为应力松弛时间除以事件持续时间。'),
v(r't_s','Shear communication time','剪切传播时间','s','Small-disturbance elastic communication scale over Lg; not a universal cavity-collapse time.','跨越 Lg 的小扰动弹性传播尺度；不是通用腔体塌缩时间。'),
v(r't_{\mathrm{poro}}','Poroelastic drainage time scale','孔弹性排水时间尺度','s','Diffusion-scale solvent/network pressure equilibration under the stated linear approximation.','在指定线性近似下溶剂／网络压力平衡的扩散时间尺度。'),
],
}
