"""Reviewed Chinese equation titles; untranslated titles must fail the build.

The English keys are the original equation classifications. Translation retains
their assumption, approximation, identity and necessary-condition qualifiers.
"""

TITLES_ZH = {
    # Chapter 1: cavity mechanics and directional jets.
    'Prescribed initial and boundary conditions': '给定的初始条件与边界条件',
    'Exact continuity within the spherical model': '球形模型内的精确连续性关系',
    'Derived velocity potential': '推导得到的速度势',
    'Exact Eulerian and moving-point derivatives': '精确的欧拉导数与运动点导数',
    'Derived inertial pressure': '推导得到的惯性压力',
    'Newtonian stress and capillary boundary condition': '牛顿流体应力与毛细边界条件',
    'Rayleigh–Plesset under the declared assumptions': '所述假设下的 Rayleigh–Plesset 方程',
    'Pressure composition requiring thermodynamic closure': '需要热力学闭合的压力组成关系',
    'Exact kinetic-energy integral in the spherical model': '球形模型内的精确动能积分',
    'Exact product-rule derivatives': '乘积求导法则的精确应用',
    'Derived mechanical-energy balance': '推导得到的机械能平衡',
    'Independent dissipation and conservation check': '独立的耗散与守恒检验',
    'Idealized collapse initial-value problem': '理想化塌缩的初值问题',
    'Exact chain rule and integrating factor': '精确的链式法则与积分因子',
    'Integrated speed with initial constant and branch': '含初始积分常数与分支选择的速度积分解',
    'Exact separation and nondimensionalization': '精确的变量分离与无量纲化',
    'Evaluated beta-function coefficient': '通过贝塔函数计算的系数',
    'Independent pressure-work conservation check': '独立的压力功守恒检验',
    'Declared teaching calculation': '采用明确给定参数的教学计算',
    'Ideal-trajectory diagnostic, not a physical limit': '理想轨迹的诊断指标，而非物理极限',
    'Definition of local pressure impulse': '局部压力冲量的定义',
    'Exact fixed-position integrated incompressible momentum': '固定位置处不可压缩动量方程的精确时间积分',
    'Short-event reduced pressure-impulse model': '短时事件的简化压力冲量模型',
    'Exact straight-column solution of the reduced model': '简化模型中直液柱的精确解',
    'Declared impulse calculation and applicability diagnostics': '采用给定参数的冲量计算与适用性诊断',
    'Geometry definition and exact symmetry identity': '几何定义与精确的对称性恒等式',
    'Bulk conservation and Newtonian constitutive assumption': '体相守恒律与牛顿流体本构假设',
    'Kinematic condition and clean-interface traction': '运动学条件与洁净界面牵引',
    'Inviscid pre-impact moving-interface closure': '冲击前无黏运动界面的闭合关系',
    'Exact spherical recovery of the potential closure': '势流闭合关系对球形模型的精确恢复',
    'Compressibility applicability diagnostics': '可压缩性适用性诊断',
    'Original formulas quoted for defense 1': '答辩问题 1 引用的原始公式',
    'Original formulas quoted for defense 2': '答辩问题 2 引用的原始公式',
    'Original formulas quoted for defense 3': '答辩问题 3 引用的原始公式',
    # Chapter 2: optical heating and finite PFC inventory.
    'Prescribed optical profile': '给定的光学分布',
    'Exact integral of the prescribed profile': '给定分布的精确积分',
    'Derived interception fraction': '推导得到的截获比例',
    'Temporal profile definition': '时间分布的定义',
    'Beer–Lambert constitutive model and solution': 'Beer–Lambert 本构模型及其解',
    'Derived optical-energy balance': '推导得到的光能平衡',
    'Reduced heat equation and Fourier constitutive law': '简化热传导方程与傅里叶本构定律',
    'Thermal-contact boundary conditions': '热接触边界条件',
    'Diffusive scaling derived from the heat equation': '由热传导方程推导的扩散尺度关系',
    'Declared-input thermal calculation': '采用明确给定输入的热学计算',
    'Static capillary and shell-pressure control': '静态毛细压力与壳层压力对照模型',
    'Verified empirical PFP property correlation': '已核验的 PFP 物性经验关联式',
    'Verified empirical water property correlations': '已核验的水物性经验关联式',
    'Classical homogeneous capillarity approximation': '经典均相成核的毛细近似',
    'Derived critical radius and branch check': '推导得到的临界半径与分支检验',
    'Derived homogeneous barrier height': '推导得到的均相成核势垒高度',
    'Derived probability under a prescribed Poisson rate': '给定泊松事件率下推导的概率',
    'Exact compound-mass ledger under the stated closed supply': '所述封闭供给条件下化合物质量的精确收支',
    'Species phase-mass balance': '组分的分相质量平衡',
    'Exact single-component interface mass jump': '单组分界面的精确质量跃迁条件',
    'Reduced interfacial energy jump and Fourier law': '简化界面能量跃迁条件与傅里叶定律',
    'Uniform-state open-bubble first-law model': '均匀状态开放气泡的热力学第一定律模型',
    'Product-rule derivation of thermal closure': '通过乘积求导法则推导热学闭合关系',
    'Ideal-mixture constitutive control and required refinement': '理想混合物本构对照模型与所需改进',
    'Derived ideal-pressure evolution identity': '推导得到的理想气体压力演化恒等式',
    'Finite-inventory equilibrium benchmark': '有限存量的平衡基准模型',
    'Finite-mass worked calculation': '有限质量的完整示例计算',
    'Declared preparation-path enthalpy estimate': '给定制备路径的焓估算',
    'Refined constant-pressure enthalpy path': '细化的恒压焓变化路径',
    'Derived ideal-vapor inventory radius': '由理想蒸气存量推导的半径',
    'Declared optical-to-heat energy screen': '给定光能转热能过程的能量筛查',
    'Original formulas for Defense 1': '答辩问题 1 的原始公式',
    'Original formulas for Defense 2': '答辩问题 2 的原始公式',
    'Original activation-probability formula': '原始激活概率公式',
    'Original inventory and pressure formulas for Defense 3': '答辩问题 3 的原始存量与压力公式',
    'Original phase-energy and velocity-slip formulas': '原始相变能量与速度滑移公式',
    # Chapter 3: arrays, finite jets and impact.
    'Independent-event statistical model': '独立事件的统计模型',
    'Derived optical-uniformity condition': '推导得到的光学均匀性条件',
    'Continuity and potential integration': '连续性关系与势函数积分',
    'Leading unsteady-Bernoulli approximation': '非定常伯努利方程的首阶近似',
    'Coupled spherical approximation': '耦合球形近似',
    'Exact polygon geometry': '精确的多边形几何关系',
    'Symmetric constant-pressure collapse control': '对称恒压塌缩对照模型',
    'Chain rule and integrating-factor derivation': '链式法则与积分因子推导',
    'Integrated solution on the inward branch': '向内运动分支上的积分解',
    'Collapse-time quadrature and sign check': '塌缩时间的求积表达式与符号检验',
    'Leading-model energy check and fixed-total-work comparison': '首阶模型的能量检验与固定总功比较',
    'Volume-fraction definition and retarded monopole approximation': '体积分数定义与延迟单极源近似',
    'Potential-flow reduction': '势流简化模型',
    'Kinematic, initial and wall conditions': '运动学条件、初始条件与壁面条件',
    'Normal stress and material Bernoulli condition': '法向应力与随界面运动的伯努利条件',
    'Pressure-impulse control and distinct focusing budgets': '压力冲量对照模型与不同聚焦过程的收支',
    'Continuity plus Bernoulli focusing benchmark': '连续性关系与伯努利方程的聚焦基准模型',
    'Finite-mass definitions and Cauchy–Schwarz bound': '有限质量定义与柯西–施瓦茨界限',
    'Slender-jet volume conservation': '细长射流的体积守恒',
    'Newtonian stress and slender axial momentum': '牛顿流体应力与细长射流的轴向动量',
    'Inviscid-cylinder instability derivation': '无黏液柱失稳的推导',
    'Finite-flight growth and regime diagnostics': '有限飞行时间内的扰动增长与适用区间诊断',
    'Dynamic-pressure definition and steady momentum flux': '动压定义与稳态动量通量',
    'Linear transient wave equations and impact matching': '线性瞬态波动方程与冲击匹配条件',
    'Finite momentum and early-impact duration conditions': '有限动量与冲击早期持续时间的条件',
    'Observer definition and conditional impulse bound': '观测量定义与有条件的冲量界限',
    'One-way-wave energy and finite-observer Cauchy–Schwarz bound': '单向行波能量与有限观测条件下的柯西–施瓦茨界限',
    'Compressible bulk conservation and required constitutive closure': '可压缩体相守恒律与所需本构闭合关系',
    'Declared optical and mechanical allocation': '明确给定的光能与机械能分配',
    'Worked finite jet mass, speed and pressure scales': '有限射流质量、速度与压力尺度的示例计算',
    'Reference answer: original interaction and allocation formulas': '参考答案：原始相互作用与分配公式',
    'Reference answer: original finite-mass and growth formulas': '参考答案：原始有限质量与扰动增长公式',
    'Reference answer: original impact and observer formulas': '参考答案：原始冲击与观测量公式',
    # Chapter 4: fracture and intact transfer.
    'Constitutive assumption and traction identity': '本构假设与牵引恒等式',
    'Exact mechanical definitions': '精确的力学定义',
    'Derived plate parameters under constitutive assumptions': '在本构假设下推导的板参数',
    'Linear-plate energy model': '线性板的能量模型',
    'Explicit integration-by-parts boundary terms': '明确写出的分部积分边界项',
    'Derived variational identity for fixed clamps': '固定夹持条件下推导的变分恒等式',
    'Reduced transient momentum balance with explicit initial/boundary data': '含明确初始与边界数据的简化瞬态动量平衡',
    'Transient plate power identity under fixed clamps': '固定夹持条件下瞬态板的功率恒等式',
    'Conditional coupled-sheet model': '有条件的耦合薄片模型',
    'Exact time integral within the reduced plate model': '简化板模型内的精确时间积分',
    'Short-pulse free-response approximation': '短脉冲后的自由响应近似',
    'Derived term-balance estimates': '通过各项平衡推导的估算',
    'Definition with quasistatic fracture criterion': '定义与准静态断裂判据',
    'Conditional dynamic energy balance': '有条件的动态能量平衡',
    'Quasistatic plate boundary-value model': '准静态板的边值模型',
    'Derived first two radial integrations': '推导中的前两次径向积分',
    'Derived second pair of radial integrations': '推导中的后两次径向积分',
    'Exact solution of the stated linear-plate benchmark': '所述线性板基准问题的精确解',
    'Governing-equation and boundary verification': '控制方程与边界条件核验',
    'Exact geometric volume integral for the benchmark': '基准模型的精确几何体积积分',
    'Derived potential under maintained-pressure control': '维持压力控制条件下推导的势能',
    'Derived quasistatic energy-release rate': '推导得到的准静态能量释放率',
    'Derived onset threshold within the benchmark': '基准模型内推导的起始阈值',
    'Derived loading-control comparison': '推导得到的加载控制方式比较',
    'Checked teaching substitution': '已核验的教学参数代入',
    'Magnitude, geometric-validity and competing-failure checks': '数量级、几何适用性与竞争失效模式检验',
    'Adopted monotonic tensile cohesive law': '采用的单调拉伸内聚定律',
    'Exact work integral of the adopted cohesive law': '所采用内聚定律的精确功积分',
    'Cohesive admissibility teaching calculation': '内聚模型容许条件的教学计算',
    'Finite incoming state inherited from the teaching source': '沿用教学源模型的有限入射状态',
    'Explicit conditional solid-coupling allocation': '明确给定且有条件的固体耦合分配',
    'Necessary global energy and momentum screens': '全局能量与动量的必要条件筛查',
    'Failed release-energy screen': '未通过的释放能量筛查',
    'Passed necessary release and minimum-speed screens': '通过的释放与最低速度必要条件筛查',
    'Energy–momentum compatibility check': '能量–动量相容性检验',
    'Ballistic placement estimate': '弹道式定位估算',
    'Original load, impulse and work formulas': '原始载荷、冲量与功公式',
    'Original global screens': '原始全局筛查公式',
    'Original pressure-controlled benchmark formulas': '原始压力控制基准模型公式',
    'Original cohesive work and fracture criteria': '原始内聚功与断裂判据',
    'Original necessary operating-window checks': '原始工作窗口的必要条件检验',
    # Appendix A: hydrogel versus liquid.
    'Exact kinematics under incompressibility': '不可压缩条件下的精确运动学关系',
    'Constitutive assumption and exact subtraction': '本构假设与精确相减关系',
    'Static balance defining the elastic resistance': '定义弹性阻力的静态平衡',
    'Exact change of variable for expansion': '膨胀过程的精确变量代换',
    'Derived neo-Hookean elastic resistance': '推导得到的新胡克弹性阻力',
    'Limiting-state and sign checks': '极限状态与符号检验',
    'Exact work integral within the elastic model': '弹性模型内的精确功积分',
    'Work-conjugacy and small-deformation checks': '功共轭关系与小变形检验',
    'Kelvin–Voigt closure and exact radial kinematics': 'Kelvin–Voigt 闭合关系与精确径向运动学',
    'Momentum law and explicitly evaluated integrals': '动量定律与明确求值的积分',
    'Derived intact-medium radial control': '推导得到的完整介质径向对照模型',
    'Derived mechanical energy balance': '推导得到的机械能平衡',
    'Teaching-input substitution': '教学输入参数的代入',
    'Finite work-budget comparison': '有限功预算的比较',
    'Signed-pressure and positive-loss check': '有符号压力与正耗散检验',
    'Response-time definition': '响应时间的定义',
    'Linear constitutive check for the chosen dashpot': '所选黏性阻尼元件的线性本构检验',
    'Teaching response-time comparison': '响应时间的教学比较',
    'Separate compressibility diagnostic': '独立的可压缩性诊断',
    'Darcy/storage approximation and derived diffusion': '达西流动与储存近似及所推导的扩散关系',
    'Original radial control recalled': '回顾原始径向对照模型',
    'Original pressure and work formulas recalled': '回顾原始压力与功公式',
    'Original event-response formulas recalled': '回顾原始事件响应公式',
    'Original load and interface-work accounting': '原始载荷与界面功的收支核算',
}


def equation_title_zh(kind):
    """Require an explicit reviewed title instead of silently emitting English."""
    try:
        return TITLES_ZH[kind]
    except KeyError as error:
        raise ValueError(f'Missing Chinese equation title: {kind}') from error
